### ISSUE TITLE
[Bug]: Timed out waiting for container port to open

### ISSUE THREAD

**Issue by bakarJc** [testcontainers/testcontainers-java#7529] opened 2023-09-14 17:09 UTC
### Module

Core

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:32:30 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.22.1 (118664)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:38 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

[4125](https://github.com/testcontainers/testcontainers-java/issues/4125) is still reproducible

I am still facing the error "timed out waiting for container ports to open" when running,

@Container static GenericContainer<?> eventStoreContainer = new GenericContainer("eventstore/eventstore:release-4.1.3").withExposedPorts(1113, 2113);

I have a feeling it might be a Mac specific issue as my teammates don't get this running the same test on Intel machines running Ubuntu. I tried connecting to a remote Docker engine running on an Ubuntu EC2 instance but still get the error

I've also confirmed by running docker ps that the container listens on 1112-1113/tcp, 2112-2113/tcp

Side note: The specific version release-4.1.3 of eventstore is not compatible with ARM64 which is also why i used a remote docker engine, but I have also tried on my local machine with an eventstore version compatible with ARM64 ([23.6.0-alpha](https://hub.docker.com/layers/eventstore/eventstore/23.6.0-alpha-arm64v8/images/sha256-93ff6ca11ec6e2b70d98699447e29fc58c9bc89cf156374970a5130b70afcc9b?context=explore)

### Relevant log output

```shell
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32771, 32772] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:102)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	... 58 more
```

**Comment by eddumelendez** [comment] 2023-10-02 20:06
I tried with ARM M1 using Docker for Desktop 4.24 and with a remote docker. As mentioned in [this comment](https://github.com/testcontainers/testcontainers-java/issues/4125#issuecomment-926319359) consider reporting this behavior to docker engine instead. Also, this is a duplicate of #4125

**Closed by eddumelendez** 2023-10-02 20:06 UTC
Labels: type/bug, resolution/duplicate
