### ISSUE TITLE
SAP Hana container 

### ISSUE THREAD

**Issue by jakobbraun** [testcontainers/testcontainers-java#3550] opened 2020-12-02 11:07 UTC
How about adding a container for [SAP HANA](https://hub.docker.com/_/sap-hana-express-edition/)?

In case it is intended to integrate it I would be happy to contribute (I already have a working prototype...).

**Comment by jakobbraun** [comment] 2020-12-02 11:09
I just saw that there already is a PR: https://github.com/testcontainers/testcontainers-java/pull/3017

**Comment by bsideup** [comment] 2020-12-02 11:09
Duplicate of #1337, also see #3017 

it looks like the technology isn't very container friendly, plus comes with a licensing issue - not something that we can easily add to our "supported" modules

**Closed by bsideup** 2020-12-02 11:09 UTC
