### ISSUE TITLE
[Bug]: DockerComposeContainer won't use local docker auth file when withLocalCompose(false)

### ISSUE THREAD

**Issue by liang-shen** [testcontainers/testcontainers-java#5984] opened 2022-10-11 07:05 UTC
### Module

Core

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

x86

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I need use my private docker repo. When run the service in the docker compose file,
```
new DockerComposeContainer<>(new File(composeFile))
                        .withExposedService(service, servicePort)
                        .withLocalCompose(false)
```
the image pull will fail with error 
```
Head "https://xxxx.jfrog.io/v2/xxxx/manifests/xxxx": unknown: Authentication is required
```

**Comment by kiview** [comment] 2022-10-11 08:38
Hey @liang-shen, can you try out if pulling the image works when you are using `GenericContainer` directly? 

We should have explicit support for authenticated image pulling (see https://github.com/testcontainers/testcontainers-java/blob/fc3d60099165c9f73689ee3269370c5347492513/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L195), even in the case of using containerized `DockerComposeContainer`, so I would like to triage if the issue is really about `DockerComposeContainer` in your case.

**Comment by liang-shen** [comment] 2022-10-18 02:34
sorry for late reply. yes, you are right, the issue isn't because of the pulling. it is because my compose file is using new sync (extend), the current approach, parsing yaml file, won't be able to capture the image file name 
my findings,

1. yaml file MUST have version field ( should adjust the ParsedDockerComposeFile::parseAndValidate() to allow the latest sync )
2. if could, should just use "docker-compose -f xxx.yml config " to get the merged yaml file. 

```
services:
  child_service:
    extends:       
       file: common-compose.yml
      service: base_service
```

**Comment by kiview** [comment] 2022-10-18 10:25
Sorry, I did not fully understand if this is an issue with your specific Docker-Compose file here (it seems like it) or Testcontainers. I'll close this issue for now, since the initially mentioned issue is invalid (not using the existing authentication), but feel free to open a new specific issue.

**Closed by kiview** 2022-10-18 10:25 UTC
Labels: type/bug, area/docker-compose, resolution/waiting-for-info
