### ISSUE TITLE
Shutdown hook

### ISSUE THREAD

**Issue by Auriium** [testcontainers/testcontainers-java#3889] opened 2021-03-16 20:20 UTC
Launching a testcontainer in a maven plugin in order to generate code conveniently with jooq and flyway, but on shutdown i get this exception:

`Exception in thread "Thread-5" java.lang.NoClassDefFoundError: org/testcontainers/utility/PathUtils
	at org.testcontainers.utility.MountableFile.lambda$deleteOnExit$0(MountableFile.java:292)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.testcontainers.utility.PathUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 2 more`
	
It always arrives after the build success/failure message from Maven, and although it doesn't fail builds directly, it seems to fail
them consistently on my CI platform.

I believe this has something to do with how testcontainers and maven interact with shutdown hooks, and if so a possible solution
would be to add an API method to allow the starting of a testcontainer without shutdown hooks (That way hacky solutions like
intercepting the shutdown hook via reflection don't need to be used to ensure that if used in a maven plugin it does not fail the build)

**Comment by Auriium** [comment] 2021-03-17 01:14
#1454

**Comment by bsideup** [comment] 2021-03-17 07:10
Duplicate of #1454 (see my answer there)

**Closed by bsideup** 2021-03-17 07:10 UTC
