### ISSUE TITLE
Could not find a valid Docker environment exception

### ISSUE THREAD

**Issue by nitinbodke** [testcontainers/testcontainers-java#3345] opened 2020-10-14 15:49 UTC
I am following article https://www.baeldung.com/docker-test-containers for Docker Compose Module.
My test class: https://github.com/eugenp/tutorials/blob/master/testing-modules/test-containers/src/test/java/com/baeldung/testconainers/DockerComposeContainerLiveTest.java
Docker file: https://github.com/eugenp/tutorials/blob/master/testing-modules/test-containers/src/test/resources/test-compose.yml
**Docker version:** 19.03.13, build 4484c46d9d
**JDK:** openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
**OS:** macOS Catalina 10.15.7 (19H2)

I am getting same exception :(
I have tried following things:
1. As mentioned in this discussion, changing /var/run/docker.sock permissions to 777
2. Adding `DOCKER_HOST = unix:///var/run/docker.sock` to testcontainers.properties
None of this worked for me! Any clues?

`
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:214)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:206)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:132)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:174)
	at org.testcontainers.containers.DockerComposeContainer.<init>(DockerComposeContainer.java:134)
	at org.testcontainers.containers.DockerComposeContainer.<init>(DockerComposeContainer.java:118)
	at org.testcontainers.containers.DockerComposeContainer.<init>(DockerComposeContainer.java:114)
	at com.symantec.saep.appcontrol.rule.generator.DockerComposeContainerLiveTest.<clinit>(DockerComposeContainerLiveTest.java:16)
	... 17 more
`

_Originally posted by @nitinbodke in https://github.com/testcontainers/testcontainers-java/issue_comments/708407883_

**Comment by bsideup** [comment] 2020-10-15 09:56
Duplicate of #3166

**Closed by bsideup** 2020-10-15 09:56 UTC

**Comment by nitinbodke** [comment] 2020-10-15 15:41
@bsideup I do faced issue reported at #3166 
It was fixed by upgrading to version '1.15.0-rc2'.
After this, I faced above issue. Is this being fixed?
