### ISSUE TITLE
OutOfMemoryError when copyFileToContainer used on large file

### ISSUE THREAD

**Issue by findepi** [testcontainers/testcontainers-java#2863] opened 2020-06-12 21:24 UTC
I want to copy a large installation archive into a container using `GenericContainer#withCopyFileToContainer`
Since the process runs with certain ("reasonable") `-Xmx`, it hits a limit:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
	at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:244)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:454)
	at java.base/java.io.InputStream.transferTo(InputStream.java:705)
	at java.base/java.nio.file.Files.copy(Files.java:3119)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:326)
	at org.testcontainers.utility.MountableFile.transferTo(MountableFile.java:300)
	at org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:257)
	at org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:234)
	at org.testcontainers.containers.GenericContainer$$Lambda$434/0x0000000800408840.accept(Unknown Source)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:397)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
	at org.testcontainers.containers.GenericContainer$$Lambda$414/0x0000000800402440.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at org.testcontainers.lifecycle.Startables$$Lambda$411/0x0000000800401440.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment] 2020-09-11 06:24
.

**Comment by jandry** [comment] 2023-05-30 13:27
I ran into this issue last friday after upgrading from testcontainers 1.18.0 to 1.18.1. (same gitlab runner)
I reproduced it on my project and solved it just reverting the testcontainers version

**Comment by eugene-kuntsevich** [comment] 2023-06-02 13:11
The same issue for me after migrating to 1.18.3
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:62)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:91)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:259)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:169)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:206)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:713)
	at java.base/java.io.InputStream.transferTo(InputStream.java:783)
	at java.base/java.nio.file.Files.copy(Files.java:3213)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:362)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:371)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:371)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:371)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:371)
	at org.testcontainers.utility.MountableFile.transferTo(MountableFile.java:327)
	at org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:306)
	at org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:282)
	at org.testcontainers.containers.GenericContainer$$Lambda$422/0x0000000800eaa290.accept(Unknown Source)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:430)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.testcontainers.containers.GenericContainer$$Lambda$391/0x0000000800e8e828.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:727)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:339)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:260)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:191)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:274)
```

**Comment by jandry** [comment] 2023-06-07 05:11
I confirm, try 1.18.1, 1.18.2, 1.18.3, same issue. Stay in 1.18.0 is only solution I found for the moment

**Comment by eddumelendez** [comment] 2023-06-07 06:58
Thanks for reporting the issue. O do not have any change related to this on top of my hrad but will take a deep look on what changed between 1.18.0 and 1.18.1

**Comment by findepi** [comment] 2023-06-07 07:12
@eddumelendez would you be interested in taking a look at https://github.com/testcontainers/testcontainers-java/pull/2864 ?

**Comment by eddumelendez** [comment] 2023-06-07 07:48
I just notice this is an old issue but some users hit into it in 1.18.1. Also, I see an update in the dependency that can be related to this issue. Since I do not have a reproducer, Can you please use `org.apache.commons:commons-compress:1.22.0` instead of `org.apache.commons:commons-compress:1.23.0`?

**Comment by eugene-kuntsevich** [comment] 2023-06-07 09:37
> I just notice this is an old issue but some users hit into it in 1.18.1. Also, I see an update in the dependency that can be related to this issue. Since I do not have a reproducer, Can you please use `org.apache.commons:commons-compress:1.22.0` instead of `org.apache.commons:commons-compress:1.23.0`?

Thanks for proposal, I tried but it didn't help

**Comment by jandry** [comment] 2023-10-04 10:37
I proposed a working workaround here https://github.com/testcontainers/testcontainers-java/issues/7239#issuecomment-1746603941

**Comment by jandry** [comment] 2023-10-04 20:56
Seems same as https://github.com/testcontainers/testcontainers-java/issues/7239

**Comment by realalknowles** [comment] 2024-01-19 13:42
I was able to work around this by using the deprecated 'withFileSystemBind'.

I did not spend a great deal of time looking into the source code but I am not sure why this has been deprecated in favour of `withCopyFileToContainer`. If you need to expose large files you would want to avoid copying anything, so the volume-based implementation makes sense. In my case, I was exposing spark jobs to a spark cluster, so JARs are massive.

**Comment by gba-foundever** [comment] 2024-01-27 11:29
A fix proposal has been pushed here https://github.com/testcontainers/testcontainers-java/issues/7239
it's working for me

**Comment by eddumelendez** [comment] 2024-07-04 22:06
#8409 has been merged and it should fix the issue.

**Closed by eddumelendez** 2024-07-04 22:06 UTC
Labels: resolution/acknowledged
