### ISSUE TITLE
wait until container started - doesn't end and in the meantime creates multiple containers (MySQLContainer)

### ISSUE THREAD

**Issue by ori-n** [testcontainers/testcontainers-java#511] opened 2017-12-05 15:03 UTC
I tried this simple code:
`        try (MySQLContainer mySQLContainer = new MySQLContainer()) {
            mySQLContainer.start();
            mySQLContainer.stop();
        }
`
In the log I get:
[INFO] 2017-12-05 16:50:48,709 [main]  🐳 [mysql:latest] waitUntilContainerStarted - Waiting for database connection to become available at jdbc:mysql://localhost:32770/test using query 'SELECT 1'

And in the meantime containers are created every 2 min:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS
7504e73de3d5        mysql:latest        "docker-entrypoint..."   11 minutes ago      Up 11 minutes       0.0.0.0:32770->3306/tcp
1ae62c3a699c        mysql:latest        "docker-entrypoint..."   13 minutes ago      Up 13 minutes       0.0.0.0:32769->3306/tcp

Am I doing something wrong. Tries both on docker on windows and docker on ubuntu and got the same results

**Comment by kiview** [comment] 2017-12-05 21:31
Hi @ori-n, can you please share a more complete example of your code?
Are you using testcontainers in a JUnit context or somewhere else?

**Comment by ori-n** [comment] 2017-12-06 03:48
Below is the complete function - I'm using junit 
 
```
    @Test
    public void runMySql() throws Exception {
        try (MySQLContainer mySQLContainer = new MySQLContainer()) {
            mySQLContainer.start();
            // connect to the db here
            mySQLContainer.stop();
        }
    }

```

**Comment by kiview** [comment] 2017-12-07 23:07
Can't reproduce this behavior on Docker for Windows. Are both containers removed once the tests have finished?

**Comment by ori-n** [comment] 2017-12-08 08:39
I tried both win and linux. It simply gets stuck. Did you try the exact code? Maybe i can try to change the code.
The mysql I use is base on alpine

Thanks,
Ori

________________________________

**Comment by kiview** [comment] 2017-12-08 08:55
I tried your exakt code on the current master branch of testcontainers and it works as expected.

How is it possible for your `MySQLContainer` to be alpine based? If you don't specify any constructor paramters, the container will use `mysql:latest`, which is Debian based (see https://hub.docker.com/_/mysql/).

Did you override your local `mysql:latest` manually on your system?

**Comment by ori-n** [comment] 2017-12-08 08:58
Sorry. Alpine before was a mistake. I did not override

Thanks,
Ori

________________________________

**Comment by kiview** [comment] 2017-12-09 10:47
Can you maybe upload a complete example project on Github?
Also, what's your Docker version?

**Comment by pol12va** [comment] 2018-03-14 21:13
@kiview 
Please take a look at https://github.com/pol12va/testcontainers-demo. I'm having exactly the same issue with MySQL container. Tried with different mysql docker images and different testcontainers versions.
Docker version: Version 17.12.0-ce-mac55 (23011)

**Comment by kiview** [comment] 2018-03-15 10:22
@pol12va 
Thanks for your example, I can reproduce the described behavior. I will look into this.

**Comment by jvujcic** [comment] 2018-07-31 17:51
@kiview 
Is there any progress on this. I'm also stuck at
 Waiting for database connection to become available at jdbc:mysql://localhost:32770/test using query 'SELECT 1'

**Comment by johnedmonds** [comment] 2018-09-13 23:51
I fixed this by adding the mysql connector dependency to my test.

**Comment by EvgeniGordeev** [comment] 2018-12-12 19:09
Adding mysql connector made it work for  `mysql:5.7.24`, but not for `mysql:8.0.13`.

**Comment by guss77** [comment] 2019-01-20 14:40
The problem with MySQL 8 could be because of the different authentication scheme introduced in MySQL 8. This is likely the same problem as issue #736.

**Comment by rnorth** [comment] 2019-04-28 10:21
The spawning of multiple containers may be fixed by #1433

**Comment by rui-ferreira** [comment] 2019-07-03 13:27
If you manually connect to the container's DB, while it's "waiting for database connection to become available", the loop resumes. This is just a hint on what may be wrong, not a workaround.

**Comment by rnorth** [comment] 2019-10-01 19:35
I’m going to close. As mentioned previously #1433 should have resolved this. If the issue still occurs then of course please reopen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by rnorth** 2019-10-01 19:35 UTC
Labels: type/bug
