### ISSUE TITLE
Remove coupling / dependency on JUnit 4 and the TestRule class

### ISSUE THREAD

**Issue by lprimak** [testcontainers/testcontainers-java#3548] opened 2020-12-01 01:36 UTC
For JUnit 5 tests, testcontainers dependency forces usage of JUnit 4, which should not be necessary.
This causes people accidentally using JUnit 4 constructs in JUnit 5-based test harnesses without knowing it.

JUnit 4 shouldn't be a transitive dependency of testcontainers, usually by putting
`<optional>true</optional>` into maven pom file

The issue is below 
```
public class GenericContainer<SELF extends GenericContainer<SELF>>
        extends FailureDetectingExternalResource
```
and then
```
import org.junit.rules.TestRule;
public class FailureDetectingExternalResource implements TestRule {
```

The above should not be inheriting from TestRule. If that's necessary, there should be JUnit 4 and 5 versions of this class.

**Comment by bsideup** [comment] 2020-12-01 09:04
Duplicate of #970

**Closed by bsideup** 2020-12-01 09:04 UTC
