### ISSUE TITLE
Enable reuse in src/test/resources/testcontainers.properties file is ignored

### ISSUE THREAD

**Issue by SVynnytska** [testcontainers/testcontainers-java#4223] opened 2021-07-01 11:12 UTC
Due to [Custom configuration](https://www.testcontainers.org/features/configuration/)
`The classpath testcontainers.properties file may exist within the local codebase (e.g. within the src/test/resources directory) 
`

I have added `src/test/resources/testcontainers.properties` file with the content
```
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
testcontainers.reuse.enable=true
```
But during running tests locally I got this error
 ```
Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /Users/username/.testcontainers.properties
```
and on Jenkins pipelines 
```
Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /root/.testcontainers.properties
```
So, `src/test/resources/testcontainers.properties` file is ignored

**Comment by bsideup** [comment] 2021-07-01 11:12
Duplicate of #3780 and others, please see the comments there

**Closed** 2021-07-01 11:13 UTC
