### ISSUE TITLE
Database containers launched via JDBC URL scheme using custom registry

### ISSUE THREAD

**Issue by vinchauhan** [testcontainers/testcontainers-java#3228] opened 2020-09-13 03:46 UTC
Database containers launched via JDBC URL cannot be pulled from custom registry, the JDBC URL defaults the image to be pulled from docker hub.

There should be a feature to parse the JDBC url even from custom registry like

jdbc:tc:custom.docker.registry.com/images/postgresql:9.6.8:///databasename

**Comment by bsideup** [comment] 2020-09-14 09:01
Duplicate of #4

**Closed by bsideup** 2020-09-14 09:01 UTC
