### ISSUE TITLE
Failed to obtain R2DBC Connection; nested exception is java.net.UnknownHostException

### ISSUE THREAD

**Issue by javalub15** [testcontainers/testcontainers-java#5402] opened 2022-05-31 13:27 UTC
When I uprgraded version for testcontainers from 1.16.3 to 1.17.0
my test started to fail with exception:

```
Failed to obtain R2DBC Connection; nested exception is java.net.UnknownHostException: 
Failed to resolve 'localhost:22467;encrypt=false' after 3 queries 
org.springframework.dao.DataAccessResourceFailureException: 
```

I use MSSQLServerContainer and r2dbc spring framework 

I don't see any specific changes in release notes for 1.17.0 version that could break it. 
Any ideas ?

**Comment by eddumelendez** [comment] 2022-07-08 22:33
Hi @javalub15, sorry for the delay. Do you have any minimal sample to reproduce the issue with the latest version 1.17.3?

**Comment by eddumelendez** [comment] 2022-10-05 03:26
Closing because there is no reply. Feel free to reopen it.

**Closed by eddumelendez** 2022-10-05 03:26 UTC
Labels: resolution/waiting-for-info
