### ISSUE TITLE
GenericContainer container contains import for org.junit.runner/runners Description/Statement

### ISSUE THREAD

**Issue by khmarbaise** [testcontainers/testcontainers-java#2013] opened 2019-10-28 18:12 UTC
Currently the `GenericContainer` class contains dependencies into JUnit 4 framework via the following import:
```java
import org.junit.runner.Description;
import org.junit.runners.model.Statement;
...
```
and there is a small number of methods which uses those things where the public methods have already been marked `@Deprecated`. This dependency causes issues related to usage of JUnit Jupiter only ...(cause the dependency to JUnit 4 is unfortunately needed).

The question is: When will such dependencies removed or expressed different: When will the deprecated marked methods being removed including the JUnit 4 dependency? Is there any documentation how this will be handled? Unfortunately I couldn't find something about this?

**Comment by khmarbaise** [comment] 2020-01-26 19:52
This should be kept cause it's current state.

**Comment by bsideup** [comment] 2020-01-26 19:58
Duplicate of https://github.com/testcontainers/testcontainers-java/issues/970

**Closed by bsideup** 2020-01-26 19:58 UTC
