### ISSUE TITLE
Test JUnit 5 extension is not public, preventing extensions ordering

### ISSUE THREAD

**Issue by jponge** [testcontainers/testcontainers-java#3505] opened 2020-11-22 21:12 UTC
The JUnit 5 extension is package-protected and can only be used using the `@TestContainers` meta-annotation.

This is a serious design issue as JUnit 5 allows multiple extensions to be applied using `@ExtendWith`.
This is not just cosmetic: ordering can be important when applying extensions.

As it is now the TestContainers extension does not want to be composed with other extensions, breaking the JUnit 5 extension model.

**Comment by bsideup** [comment] 2020-11-23 10:21
Duplicate of #2045

**Closed by bsideup** 2020-11-23 10:21 UTC
