### ISSUE TITLE
Init script parsing issue of line endings on windows

### ISSUE THREAD

**Issue by Mawster** [testcontainers/testcontainers-java#1465] opened 2019-05-14 11:11 UTC
Hi guyz,

I'm working on a windows machine and the files of the project have windows line endings. We have a script which should initialize our oracle database - so we added the "withInitScript" option on container start.

As soon as the initialization starts we get the following error:
java.sql.SQLException: Invalid SQL type: sqlKind = UNINITIALIZED

So I tried just a little test statement:
`CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255) 
);`

Still the same error. So I debugged into the code and found the Problem:
The last statement which should be executed was:
`\r` 
and so the init script failed.

After switching from CRLF to LF everything works, but I would say also Windows line endings should be handled properly?

It should be just a small change in ScriptUtils.java Line 186 ?

**Comment by kiview** [comment] 2019-05-14 13:14
Thanks for raising the issue and investigating the problem @Mawster.
I don't think the problem is in line 186 though, since this code handles comments (although this is also a problem there).

We probably need to add `\r` in line 209 as well.

Would you like to contribute this, since you can directly test this on your machine?

**Comment by ppfeiler** [comment] 2019-05-14 14:24
@kiview I tried to fix it. My tests are now working.

**Comment by rnorth** [comment] 2019-05-21 20:32
Fix released in [1.11.3](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.3).

**Closed by rnorth** 2019-05-21 20:32 UTC
Labels: modules/jdbc, os/windows, type/bug
