### ISSUE TITLE
`DockerComposeContainer.withExposedService()` ignores `container_name` directive in Docker Compose YAML file

### ISSUE THREAD

**Issue by nhooey** [testcontainers/testcontainers-java#1490] opened 2019-05-21 17:16 UTC
When the Docker Compose configuration YAML file that is passed to `DockerComposeContainer`, any exposed services that have `container_name` set in the YAML file will fail to be considered started because TestContainers isn't able to see their status.

The `WaitStrategy` classes need to check for the correct container name.

**Comment by mumukiller** [comment] 2019-05-22 20:43
I suppose it's a duplicate https://github.com/testcontainers/testcontainers-java/issues/1151

**Comment by bsideup** [comment] 2019-07-01 09:45
Duplicate of #1151

**Closed by bsideup** 2019-07-01 09:45 UTC
