### ISSUE TITLE
Cannot use withFileSystemBind on Windows

### ISSUE THREAD

**Issue by torstenkuhnhenne** [testcontainers/testcontainers-java#3536] opened 2020-11-26 10:23 UTC
When I try to use `withFileSystemBind` on Windows I get an parse error. After some debugging I found out that the problem is the `new File(..).toURI().toString()` in the class `MountableFileSystem` and also there was a bug in the class `Bind` from docker-java. The second one is fixed in release 3.2.6. But even with the new version it does not work because the `toURI()` changes all `\` from the windows path to `/` and after that `Bind.parse(String)` throws an exception because the regex pattern looks for `\`

The problem is that `Bind.parse(String)` uses `:` as separator and this is also used in normal windows paths, e.g. `c:\temp\mypath`.

Summary:
* I call `withFileSystemBind("c:\temp\mypath", "/mypath", BindMode.READ_WRITE)`
* In `MountableFile.forHostPath()` this is converted to `file:/c:/temp/mypath`
* `Bind.parse(String)` throws an exception

Possible solution: Use `new File(..).toString()` in `MountableFile.forHostPath()` or maybe `new File(path).getAbsolutePath().toString()`. The second solution is simular to the code path with the `Path` parameter. As far as I understand it is not possible to change the regex pattern in `Bind.parse()` because `..:/...` is the normal docker syntax for a volume mapping and you cannot use a negative lookahead for `/`.

Testcontainers: 1.15.0
Docker Desktop with Docker Engine 19.03.13

**Comment by bsideup** [comment] 2020-11-26 11:17
Duplicate of #3493

**Closed by bsideup** 2020-11-26 11:17 UTC
