### ISSUE TITLE
[Enhancement]: Compilation will fail if junit4 is excluded from compile classpath

### ISSUE THREAD

**Issue by SButterfly** [testcontainers/testcontainers-java#6000] opened 2022-10-20 11:55 UTC
### Module

Core

### Proposal

In my project, we exclude all junit4 libraries and left only junit5-jupiter libraries.
However, the project can't compile due to missing java class `org.junit.rules.TestRule`

```
SOME_PATH/TestcontainersConfiguration.java:30: error: cannot access TestRule
            .withInitScript("testcontainers/init.sql")
            ^
  class file for org.junit.rules.TestRule not found
```

Ideally, I want that test containers wouldn't depend on any specific test library.

**Comment by kiview** [comment] 2022-10-21 09:10
Thanks for raising the PR @SButterfly. This is a duplicate of https://github.com/testcontainers/testcontainers-java/issues/970. We are aware of this issue and it is part of our roadmap.

**Closed by kiview** 2022-10-21 09:10 UTC
Labels: type/enhancement
