### ISSUE TITLE
Field name with 'end' causes init script to fail 

### ISSUE THREAD

**Issue by rrhartjr** [testcontainers/testcontainers-java#1377] opened 2019-04-09 14:51 UTC
Creating a MySQL container with an init script:
```
MySQLContainer c = (MySQLContainer) new MySQLContainer("mysql:5.7.23").withInitScript("create_schema.sql");
```

This works fine:
```
CREATE TABLE test (
    id INT,
    date_finish VARCHAR(1)
);
CREATE TABLE test2 (
    id INT
);
```

This fails:
```
CREATE TABLE test (
    id INT,
    date_end VARCHAR(1)
);
CREATE TABLE test2 (
    id INT
);
```

Debugging reveals that it appears to be erroneous treating it as a compound statement and decrementing the depth:

![image](https://user-images.githubusercontent.com/752559/55810348-67e2ad80-5ab5-11e9-95de-853ac2f5e03f.png)

**Comment by kalexmills** [comment] 2019-04-16 01:43
This is a duplicate of #1235, vote there. For a workaround rollback to version `1.10.3`.

**Closed** 2019-04-17 07:46 UTC
