### ISSUE TITLE
Make Testcontainers annotation inheritable

### ISSUE THREAD

**Issue by heruan** [testcontainers/testcontainers-java#1844] opened 2019-09-09 13:13 UTC
I'm using the `junit-jupiter` integration to create a common superclass for my tests, but `@Testcontainers` isn't `@Inherited` so my test classes don't inherit it. Also, `TestcontainerExtension` is private so I cannot create my own annotation as a workaround.

Would it be possible to have `@Testcontainers` inheritable?

**Comment by bsideup** [comment] 2019-09-09 13:16
Thanks for the report!

It seems to be a duplicate of #1843

**Closed by bsideup** 2019-09-09 13:16 UTC
Labels: resolution/duplicate

**Comment by heruan** [comment] 2019-09-09 13:47
Darn, 5 hours late! 😅
