### ISSUE TITLE
`LocalDockerCompose` does not support Docker Compose v2

### ISSUE THREAD

**Issue by kamilkloch** [testcontainers/testcontainers-java#5596] opened 2022-07-13 14:23 UTC
### Module

Core

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

`LocalDockerCompose` does not support Docker Compose v2 (`docker compose` instead of `docker-compose`). The following error occurs:
```
Local Docker Compose not found. Is docker-compose on the PATH?
```
See https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L741

**Comment by wolfey** [comment] 2022-08-03 11:16
Yes we absolutely need this. Please also support using the docker builtin compose api via `docker compose` instead of `docker-compose`.

**Comment by eddumelendez** [comment] 2022-08-03 16:14
see #5608

**Comment by kiview** [comment] 2022-08-26 07:10
I am closing this as a duplicate of #5278.

**Closed by kiview** 2022-08-26 07:10 UTC
Labels: type/bug, area/docker-compose, resolution/acknowledged, resolution/pr-submitted
