### ISSUE TITLE
Test containers with junit 5 still includes junit 4

### ISSUE THREAD

**Issue by matejsp** [testcontainers/testcontainers-java#3753] opened 2021-02-03 08:18 UTC
We are banning the use of junit 4 dependency in our projects. This is done to ensure only junit 5 API is used. However testcontainers still includes junit as compile dependency.

When excluding it:
```
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <version>1.15.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Usage:
```
        mariaDB = new MariaDBContainer(MariaDBContainer.NAME).withDatabaseName("core");
        //mariaDB.withReuse(true);
        mariaDB.start();
```

When running junit 5 test it crashes with:
```
Caused by: java.lang.ClassNotFoundException: org.junit.rules.TestRule
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 145 more
```

If we don't exclude junit 4 as a dependency, developers start to mix junit 4 and junit 5 API.

**Comment by bsideup** [comment] 2021-02-03 19:22
Duplicate of #970

**Closed by bsideup** 2021-02-03 19:22 UTC
