### ISSUE TITLE
Is it possible to provide RocketMq module?

### ISSUE THREAD

**Issue by addname** [testcontainers/testcontainers-java#3916] opened 2021-03-22 07:04 UTC
Is it possible to provide RocketMq module? 
It is very inconvenient to use RocketMQ with GenericContainer. Many people need it, thanks

**Comment by bsideup** [comment] 2021-03-22 07:37
Hi @addname,

Seems to be a duplicate of #3348

**Closed by bsideup** 2021-03-22 07:37 UTC
