### ISSUE TITLE
[Bug]: Status 500: Mounts denied: dial unix /Users/atwong/Library/Containers/com.docker.docker/Data/osxfs.sock: connect: connection refused

### ISSUE THREAD

**Issue by alberttwong** [testcontainers/testcontainers-java#7450] opened 2023-08-30 23:31 UTC
### Module

Core

### Testcontainers version

1.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host Arch

ARM

### Docker version

```shell
atwong@Alberts-MBP-3 testcontainers-java % docker version
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:32:30 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.22.1 (118664)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:38 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### What happened?

run `./gradlew test`

### Relevant log output

```shell
Caused by:
        org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
            at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
            at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
            ... 47 more

            Caused by:
            org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:565)
                at app//org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:356)
                at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                ... 48 more

                Caused by:
                com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: Mounts denied: dial unix /Users/atwong/Library/Containers/com.docker.docker/Data/osxfs.sock: connect: connection refused
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
                    at app//org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
                    at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:453)
                    ... 50 more
```
```


### Additional Information

I'm using VirtioFS

**Comment by alberttwong** [comment] 2023-08-30 23:37
It seems like TestContainers can only use osxfs.

**Comment by eddumelendez** [comment] 2023-08-30 23:42
@alberttwong it would be very appreciated if you can share more ingo such as the docker run command you execute and I assume it work. Also, the testcontainers example that is failing for you, a reproducible example would be welcome.

**Comment by alberttwong** [comment] 2023-09-06 16:57
![Screenshot 2023-09-06 at 9 56 36 AM](https://github.com/testcontainers/testcontainers-java/assets/749093/cdb61001-7445-4ff1-9ccc-7ccf4dc6aa86)

```
atwong@Alberts-MBP-3 testcontainers-java % ./gradlew :starrocks:test
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Task :starrocks:test

Gradle Test Executor 1 > org.testcontainers.jdbc.starrocks.StarRocksJDBCDriverTest > test[0 - jdbc:mysql://hostname/databasename] STARTED

Gradle Test Executor 1 > org.testcontainers.jdbc.starrocks.StarRocksJDBCDriverTest > test[0 - jdbc:mysql://hostname/databasename] FAILED
    com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization
        at app//com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:550)
        at app//com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172)
        at app//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
        at app//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
        at app//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
        at app//org.testcontainers.jdbc.AbstractJDBCDriverTest.getDataSource(AbstractJDBCDriverTest.java:223)
        at app//org.testcontainers.jdbc.AbstractJDBCDriverTest.test(AbstractJDBCDriverTest.java:49)
        at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11.0.20/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.20/java.lang.reflect.Method.invoke(Method.java:566)
        at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at app//org.junit.runners.Suite.runChild(Suite.java:128)
        at app//org.junit.runners.Suite.runChild(Suite.java:27)
        at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
        at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11.0.20/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.20/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

        The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
            at app//com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
            at app//com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
            at app//com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
            at app//com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
            at app//com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
            at app//com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
            at app//com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
            at app//com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:444)
            at app//com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:548)
            ... 58 more

            Caused by:
            com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

            The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
                at java.base@11.0.20/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at java.base@11.0.20/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at java.base@11.0.20/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base@11.0.20/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at app//com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
                at app//com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
                at app//com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
                at app//com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
                at app//com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
                at app//com.mysql.cj.NativeSession.connect(NativeSession.java:121)
                at app//com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
                at app//com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
                ... 64 more

                Caused by:
                java.net.UnknownHostException: hostname: nodename nor servname provided, or not known
                    at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
                    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
                    at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
                    at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
                    at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
                    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1386)
                    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1307)
                    at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130)
                    at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
                    ... 67 more
```

**Comment by alberttwong** [comment] 2023-09-06 17:15
```
atwong@Alberts-MBP-3 testcontainers-java % docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *     moby                Docker Desktop                            unix:///Users/atwong/.docker/run/docker.sock
tcc                 moby                                                          tcp://127.0.0.1:57385/0
```

**Comment by alberttwong** [comment] 2023-09-06 17:15
```
atwong@Alberts-MBP-3 testcontainers-java % cat ~/.testcontainers.properties
#Modified by Testcontainers
#Wed Aug 30 16:32:11 PDT 2023
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
```

**Comment by kiview** [comment] 2023-09-13 07:11
@alberttwong Please share your Testcontainers code or ideally a reproducer project.

I am also using VirtioFS on Docker Desktop 4.22.1 and tried a couple of our internal tests without any issues.

**Comment by alberttwong** [comment] 2023-09-13 22:35
here's my git repo.... https://github.com/alberttwong/testcontainers-java

**Comment by kiview** [comment] 2023-09-14 08:29
Hey @alberttwong, can you pease share a _minimal_ reproducer, based on https://github.com/testcontainers/testcontainers-java-repro? What you just shared looks like a fork of tc-java, and I could not reproduce your issue there.

**Comment by ascopes** [comment] 2023-09-14 16:03
Same issue, mine is 

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image localstack/localstack:0.14.3
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:361)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:334)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:280)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:267)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:82)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$5(TestcontainersExtension.java:82)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:82)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:56)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
	... 9 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:565)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:356)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 10 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"error while creating mount source path '/host_mnt/Users/scopesa/.docker/run/docker.sock': mkdir /host_mnt/Users/scopesa/.docker/run/docker.sock: operation not supported"}
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:453)
	... 12 more
```

I can confirm that this works properly under the exact same settings if I use testcontainers 1.18.0 rather than 1.19.0, so this seems to be a regression.

**Comment by eddumelendez** [comment] 2023-09-14 17:09
I'm using Docker Desktop 4.23 which enables VirtioFS by default and I'm able to run [LocalStack test](https://github.com/eddumelendez/testcontainers-localstack) using Testcontainers for Java 1.19.0.

Please, when submitting an issue consider sharing a reproducible project.

I'm closing this one as can not be reproduced.

**Closed by eddumelendez** 2023-09-14 17:09 UTC
Labels: type/bug
