### ISSUE TITLE
classes conflict when using docker-java for production code

### ISSUE THREAD

**Issue by juwit** [testcontainers/testcontainers-java#2860] opened 2020-06-12 14:46 UTC
Hi there !

First, thank you for the great work. I use testcontainers since a few months, and it's great !

I have an issue in one of my app using :
* docker-java 3.2.2 for production code, with transport-zerodep
* testcontainers 1.14.3 for integration testing

This kind of code raises a `NoSuchMethodError` when executed in an integration test : 
```java
@Bean
DockerClient client(DockerClientConfig config, DockerHttpClient transport){
    return DockerClientImpl.getInstance(config, transport);
}
```
```
Caused by: java.lang.NoSuchMethodError: com.github.dockerjava.core.DockerClientImpl.getInstance(Lcom/github/dockerjava/core/DockerClientConfig;Lcom/github/dockerjava/transport/DockerHttpClient;)Lcom/github/dockerjava/api/DockerClient;
```

When digging a little, I found out that test containers embeds docker-java 3.2.0, and the classes are not shaded.  So It conflicts with my production code using docker-java 3.2.2.
It seems that this `getInstance` method was added in docker-java 3.2.2 (others are deprecated).

As a workaround, I stick with docker-java 3.2.0, and a transport-okhttp for now, but still, this issue could help someone else :)

**Comment by bsideup** [comment] 2020-06-12 19:14
Hi @juwit,

First of all, thanks for upgrading to the latest version of `docker-java` and _especially_ for trying the `zerodep` (aka Apache HttpClient5) transport! :)

There is indeed an issue when both libraries are used. The history of it is full of hard decisions, where `docker-java`'s set of dependencies was so hard to have that we decided to re-shade it and include into Testcontainers' jar.

The good news is that we worked with the `docker-java` team and extracted the API module, so the next release of Testcontainers will finally stop including `docker-java-api` classes 🎉

Expect it (1.15.0 release) to happen soon, and I hope the workaround worked fine for now.
Actually, I think you can even use 3.2.2, but, instead of calling `getInstance(config, transport)`, you can replace it with `getInstance(config).withDockerCmdExecFactory(new OkHttpDockerCmdExecFactory())`, or even `zerodep` + `DefaultDockerCmdExecFactory`. These are deprecated but fully working methods (disclaimer: I am the current maintainer of `docker-java`))

**Comment by juwit** [comment] 2020-06-13 12:36
Hi @bsideup 

Thank you for your reply.

I upgraded to docker-java 3.2.2, and used okhttp-transport with this snippet : 

```java
@Bean
DockerClient client(DockerClientConfig config){
    return DockerClientImpl.getInstance(config)
        .withDockerCmdExecFactory(new OkHttpDockerCmdExecFactory());
}
```

I'll wait for the testcontainers 1.15 release to switch to the zerodep transport (couldn't make it work)

You're doing great work with docker-java, I may open a few issues, or maybe contribute to it if I can find the time to do so.

**Comment by bsideup** [comment] 2020-06-16 09:59
@juwit thanks for your kind feedback :)

FYI I just submitted https://github.com/testcontainers/testcontainers-java/pull/2882 for that.

I will close this issue since it is a duplicate of #1113

**Closed by bsideup** 2020-06-16 09:59 UTC
Labels: area/shading, resolution/acknowledged
