### ISSUE TITLE
[Enhancement]: Allow classpath properties to enable container reuse

### ISSUE THREAD

**Issue by ptrdom** [testcontainers/testcontainers-java#7048] opened 2023-05-20 08:43 UTC
### Module

Core

### Proposal

Currently only user properties or environmental variables can enable container reuse, I cannot see a reason why classpath properties cannot also enable it.

**Comment by bsideup** [comment] 2023-05-26 19:22
Duplicate of https://github.com/testcontainers/testcontainers-java/issues/3780

**Closed by bsideup** 2023-05-26 19:22 UTC
Labels: type/enhancement
