### ISSUE TITLE
private docker registry no longer works with version 1.8.1

### ISSUE THREAD

**Issue by kiptix** [testcontainers/testcontainers-java#835] opened 2018-08-15 10:40 UTC
It works with version 1.8.0, but with 1.8.1 i got the following exception:
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: unauthorized: authentication required

OS is Linux.
Docker version 17.05.0-ce, build 89658be
~/.docker/config.json (with replaced url and token):
{
	"auths": {
		"registry.url": {
			"auth": "token"
		}
	}
}

**Comment by rnorth** [comment] 2018-08-16 21:55
Sorry @kiptix - this looks like a duplicate of #820, so I'll copy your comment over there and close this one.

**Closed by rnorth** 2018-08-16 21:55 UTC
