### ISSUE TITLE
[Bug]: PostgreSQLContainer fails to startup intermittently under GitHub Actions (not receiving STDOUT)

### ISSUE THREAD

**Issue by nefilim** [testcontainers/testcontainers-java#5978] opened 2022-10-05 01:20 UTC
### Module

PostgreSQL

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

No

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client:
   Version:           20.10.13
   API version:       1.41
   Go version:        go1.16.15
   Git commit:        a224086
   Built:             Thu Mar 31 19:20:32 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
Server:
   Engine:
    Version:          20.10.13
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.16.15
    Git commit:       906f57f
    Built:            Thu Mar 31 19:21:13 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.4.6
    GitCommit:        d71fcd7d8303cbf684[40](...)
   runc:
    Version:          1.0.0
    GitCommit:        %runc_commit
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
```

### What happened?

The Postgres container fails to startup intermittently (almost consistently) when running in Github Actions using a self hosted runner.

The logs of the failed container doesn't show all the expected logs but it does show the line the LogWaitMessageStrategy is expecting - considerable earlier than when the failure occurs. 

### Relevant log output

```shell
22:03:45.478 [main] INFO  🐳 [postgres:11] - Creating container for image: postgres:11
22:03:45.570 [main] INFO  🐳 [postgres:11] - Container postgres:11 is starting: 0a1b0472399f780e59b0aa59ace9d15c878845dd333edea5971cfe2e47cd6d12
22:04:46.179 [main] ERROR 🐳 [postgres:11] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*database system is ready to accept connections.*\s'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.PostgreSQLContainer.waitUntilContainerStarted(PostgreSQLContainer.java:139)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
	at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
	at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
	at com.xxx.capacity.predictions.PredictionServiceTest.run(PredictionServiceTest.scala:23)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
	at mill.testrunner.TestRunner$.$anonfun$runTestFramework$2(TestRunner.scala:355)
	at mill.util.Jvm$.inprocess(Jvm.scala:30)
	at mill.testrunner.TestRunner$.runTestFramework(TestRunner.scala:318)
	at mill.testrunner.TestRunner$.main(TestRunner.scala:256)
	at mill.testrunner.TestRunner.main(TestRunner.scala)
22:04:46.216 [main] ERROR 🐳 [postgres:11] - Log output from the failed container:
WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
2022-10-04 22:03:47.392 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-10-04 22:03:47.392 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-10-04 22:03:47.392 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-10-04 22:03:47.404 UTC [77] LOG:  database system was shut down at 2022-10-04 22:03:47 UTC
2022-10-04 22:03:47.408 UTC [1] LOG:  database system is ready to accept connections
```

### Additional Information

GitHub Runner version appears to be `2.279.0`

**Comment by eddumelendez** [comment] 2022-10-05 01:28
Hi @nefilim, can you share your code, please? We are testing very often Postgres with versions lower and greater than 11. The only scenario I can think of is the one when the Postgres container already contains data.

**Comment by nefilim** [comment] 2022-10-05 01:58
hi @eddumelendez sure, not much to it I'm afraid: 

```scala
  override val container: PostgreSQLContainer = PostgreSQLContainer(
    DockerImageName.parse("postgres:11"),
    databaseName = "predictions",
    username = "postgres",
    password = "password"
  )
  
  override def afterStart(): Unit = {
    import container.container.*
    Try(
      Flyway
        .configure()
        .dataSource(getJdbcUrl, getUsername, getPassword)
        .load()
        .migrate()
    ).toEither.leftMap(e => fail(s"unable to migrate schema using Flyway: $e")): @annotation.nowarn
  }  
```

**Comment by eddumelendez** [comment] 2022-10-05 02:08
I would suggest to use `testcontainers-java` directly

**Comment by nefilim** [comment] 2022-10-05 14:27
Some more information, this also seems to happen with the localstack container but no logs are available:

```shell
02:23:13.471 [io-compute-4] INFO  🐳 [localstack/localstack:1.0.4] - HOSTNAME_EXTERNAL environment variable set to localstack-v2 (to match last network alias on container with non-default network)
02:23:13.471 [io-compute-4] INFO  🐳 [localstack/localstack:1.0.4] - Creating container for image: localstack/localstack:1.0.4
02:23:13.591 [io-compute-4] INFO  🐳 [localstack/localstack:1.0.4] - Container localstack/localstack:1.0.4 is starting: 6c85f46bd6c1af57a4879fc8a41ef34bd28a0b587ef48d3641b6a1dd9dd26d39
02:24:14.723 [io-compute-4] ERROR 🐳 [localstack/localstack:1.0.4] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Ready\.
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
	at com.xxx.capacity.harvester.AbstractFetcherTest.$anonfun$createContainerResources$3(AbstractFetcherTest.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:358)
	at cats.effect.IOFiber.execR(IOFiber.scala:1332)
	at cats.effect.IOFiber.run(IOFiber.scala:139)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
02:24:14.738 [io-compute-4] ERROR 🐳 [localstack/localstack:1.0.4] - There are no stdout/stderr logs available for the failed container
```

It only happens with GitHub Actions (DIND?) - always works fine locally

**Comment by eddumelendez** [comment] 2022-10-05 14:32
are you using dind with localstack? I think you can ask localstack about it. See https://github.com/testcontainers/testcontainers-java/issues/5869#issuecomment-1262556049

**Comment by nefilim** [comment] 2022-10-05 14:35
thanks @eddumelendez - interesting thread, though I'm doubtful that is what's happening here, localstack usually succeeds in starting up, once in a while it fails too - if the outbound access was a problem it should consistently fail no?

**Comment by eddumelendez** [comment] 2022-10-05 14:37
I see you are using testcontainers-scala and to be honest not sure about the implementation. I would highly recommend to use testcontainers-java directly :)

**Comment by nefilim** [comment] 2022-10-06 21:20
It's not really reasonable to "check if this issue occur when using testcontainers-java" directly for a large project. From the stack traces shows it appears that testcontainers-scala is just a simple wrapper over the java library, I would be surprised if it's a problem with the scala wrapper. 

The problem does appear to be limited to concurrent GHA runs.

**Comment by kiview** [comment] 2022-10-07 11:13
I understand, in this case, please create an issue with https://github.com/testcontainers/testcontainers-scala. While `testcontainers-scala` is a wrapper of sorts, it has completely independent additional implementations around the actual containers abstractions, e.g. see: https://github.com/testcontainers/testcontainers-scala/blob/master/modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala

This can very well influence the startup behavior of the container in certain scenarios. As can other aspects, as outlined by @eddumelendez, such as data be already present in the PotgresSQL container. 

I'll close this issue here at `testcontainers-java` now, but I'd be happy to re-open and have a look at it, you can provide a minimal reproducer using `testcontainers-java`.

**Comment by kiview** [comment] 2022-11-28 12:55
Reopening, since we learned from [this comment](https://github.com/testcontainers/testcontainers-scala/issues/237?notification_referrer_id=NT_kwDOAE2jaLI0NTk0MTE0ODUxOjUwODgxMDQ&notifications_query=repo%3Atestcontainers%2Ftestcontainers-scala#issuecomment-1276783919), that there seems to be a situation, where STDOUT is not connected and therefore the `LogMessageWaitStrategy` fails.

However, I am not sure if we can easily debug this, since it might be a specific issue with the state of the Docker daemon in this given environment.

@nefilim do you see any way to create a reproducer that can be run locally? Either locally against in a Docker daemon on Linux (or in Codespaces), or against Docker Desktop.

**Comment by nefilim** [comment] 2022-11-29 03:19
@kiview Since troubleshooting [this issue](https://github.com/testcontainers/testcontainers-java/issues/6078) a bit: I'm wondering if the issue is lower down in the stack, perhaps there were no STDOUT logs available from the docker daemon as seen in the ryuk issue? 

I've created custom waiting strategies for use with Postgres and Localstack (has the same problem) respectively, it's been working well enough but not ideal long term. 

Another interesting data point with the ryuk issue, I've constrained the heap size of the build tool we use (mill) and haven't seen the ryuk problem again since, so you may have been right that aggressive memory usage my be putting the docker daemon into a problematic state?

**Comment by kiview** [comment] 2022-12-05 15:00
Thanks for sharing this @nefilim, this sounds very likely. I wonder what we can to reproduce or help with it, since it seems very dependent on the environment state. 

TBH, I am inclined to close the 3 issues if we assume the change in memory consumption of the build agent solved the issue for you. I'd be happy to re-open if it still occurs. WDYT @nefilim? 

Just for reference, these are the 2 other issues:
* https://github.com/testcontainers/testcontainers-scala/issues/237
* https://github.com/testcontainers/testcontainers-java/issues/6078

**Comment by kiview** [comment] 2022-12-19 14:34
I am closing the issue for now with the same reason as #6078, assuming the root cause was a broken Docker daemon state, that could be mitigated by changing the configuration of your CI. Please let us know if the issue persists and we can re-open and continue the root cause analysis @nefilim.

**Closed by kiview** 2022-12-19 14:34 UTC
Labels: type/bug
