### ISSUE TITLE
Add Support For RabbitMQ

### ISSUE THREAD

**Issue by ankurpathak** [testcontainers/testcontainers-java#1648] opened 2019-07-23 04:52 UTC
On going through documentation I can't find support for RabbitMq(https://www.rabbitmq.com).
https://www.testcontainers.org
Kindly add support for  RabbitMq as well.

**Comment by bsideup** [comment] 2019-07-23 06:18
Duplicate of #1447

**Comment by ankurpathak** [comment] 2019-07-24 22:56
@bsideup I can see #1447 merged. Which version will have that module for rabbit mq?

**Comment by bsideup** [comment] 2019-07-25 06:49
@ankurpathak it is released in 1.12.0

**Closed by bsideup** 2019-07-25 06:49 UTC
