### ISSUE TITLE
[Bug]: container.isRunning always returns false

### ISSUE THREAD

**Issue by dogruis** [testcontainers/testcontainers-java#9480] opened 2024-10-30 14:23 UTC
### Module

Core

### Testcontainers version

1.20.3

### Using the latest Testcontainers version?

Yes

### Host OS

Mac OS

### Host Arch

ARM64

### Docker version

Docker version 27.3.1, build ce12230

### What happened?

this.getcurrentcontainerinfo().getstate().getrunning() is returning wrong state all the time

**Comment by corrosive4354** [comment] 2024-10-31 02:55
Docker configuration may affect the running status of the container, especially on macOS.
If possible, try to use [ServBay](https://servbay.com) instead of Docker to run your container to see if it can solve the problem. Since ServBay's support on macOS may be more mature, it may avoid some Podman-related problems.

**Comment by eddumelendez** [comment] 2024-11-05 22:58
> this.getcurrentcontainerinfo().getstate().getrunning() is returning wrong state all the time

I am running a test using Mac M1 with Docker Desktop and Docker Engine 27.3.1.

```java
PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(DockerImageName.parse("postgres:9.6.12"));
postgres.start();
System.out.println(postgres.getCurrentContainerInfo().getState().getRunning());
```

The code above prints true, which is expected.

I am going to close this issue but feel free to share a project that reproduces the issue you described and I will reopen.

**Closed by eddumelendez** 2024-11-05 22:58 UTC
Labels: type/bug
