### ISSUE TITLE
RabbitMQContainer not working with the latest rabbitmq-management docker image

### ISSUE THREAD

**Issue by AlexCovizzi** [testcontainers/testcontainers-java#4312] opened 2021-07-29 09:02 UTC
When using the RabbitMQContainer with the latest version of rabbitmq-management docker image, the docker container is not started.
The error is caused by the RABBITMQ_DEFAULT_PASS environment variable that has been deprecated and is not supported anymore ([see this commit](https://github.com/docker-library/rabbitmq/commit/59789a4a764d3fcf63be8651c05dbfcecfa7ac10)).

**Comment by kiview** [comment] 2021-07-29 09:24
Hi @AlexCovizzi, thanks a lot for raising this issue and adding the context.
I can confirm that it does not work OOTB because of the linked changed.

However, as a simple workaround, one can simply explicitly remove the password:
```java
container.withAdminPassword(null);
```

**Comment by nmoreira** [comment] 2021-07-29 11:13
It seams to be fixed in 1.16.0 I guess...

**Comment by kiview** [comment] 2021-07-29 11:18
It should not be fixed when using the new image, at least to my knowledge.

**Comment by nmoreira** [comment] 2021-07-29 11:35
> It should not be fixed when using the new image, at least to my knowledge.

I switched to the alpine version `rabbitmq:3-management-alpine`... that's why I didn't got the issue this time...
My bad... sorry :)

**Comment by kiview** [comment] 2021-07-29 11:39
I tested with `rabbitmq:3.9.0-management-alpine`, which did not work. And indeed the commit referenced in the original comment indicates that this problem starts to appear with version `3.9.0`, which was released 6 days ago.

**Comment by nmoreira** [comment] 2021-07-29 14:20
I don't know why but my docker didn't updated my docker image tagged with `rabbitmq:3-management-alpine` to the latest one released a few days ago, so I was still running with the previous version.
I manually deleted the image and it pulled the updated one and it started to fail.
An additional workaround to the one you've suggested is to explicitly use a docker image from 3.8 version (like rabbitmq:3.8-management)

**Comment by BorisNen** [comment] 2021-08-05 18:28
> I don't know why but my docker didn't updated my docker image tagged with `rabbitmq:3-management-alpine` to the latest one released a few days ago, so I was still running with the previous version.
> I manually deleted the image and it pulled the updated one and it started to fail.
> An additional workaround to the one you've suggested is to explicitly use a docker image from 3.8 version (like rabbitmq:3.8-management)

Was just about to post the same issue. We ended up doing the workaround that you suggested.
For now we are using the latest 3.8.x version of the official image -> rabbitmq:3.8.19-alpine
Our issue and the fix for it can be seen here -> https://github.com/eclipse/dirigible/issues/1013

**Comment by mgryszko** [comment] 2022-07-15 08:50
I launched  `RabbitMQContainer` (using the provided `RabbitMQContainerJUnitIntegrationTest`) with 3.9 and 3.10 versions and the environment variable `RABBITMQ_DEFAULT_PASS` is fully supported. See the official [RabbitMQ image documentation](https://hub.docker.com/_/rabbitmq), the latest [Ubuntu entrypoint](https://github.com/docker-library/rabbitmq/blob/master/3.10/ubuntu/docker-entrypoint.sh#L13) and the latest [Alpine entrypoint](https://github.com/docker-library/rabbitmq/blob/master/3.10/alpine/docker-entrypoint.sh#L13).

This only test that fails is `RabbitMQContainerTest.shouldWorkWithSSL`, but this have be reported in #5599.

@kiview, I vote for closing this issue in favour of #5599.

**Comment by eddumelendez** [comment] 2023-10-28 01:41
I can confirm RabbitMQContainer works with latest version, see the following [example](https://github.com/eddumelendez/testcontainers-samples/blob/main/spring-boot-rabbitmq/src/test/java/com/example/consumer/SpringBootRabbitMQApplicationTests.java).

**Closed by eddumelendez** 2023-10-28 01:41 UTC
Labels: type/feature, resolution/acknowledged, good first issue
