### ISSUE TITLE
Support Healthcheck specification at container launch time or a wait strategy for a command

### ISSUE THREAD

**Issue by mkobit** [testcontainers/testcontainers-java#1529] opened 2019-06-04 13:51 UTC
[`docker container run`](https://docs.docker.com/engine/reference/commandline/run/) supports different arguments for an alternative healthcheck at launch time:

> * `--health-cmd` |   | Command to run to check health
-- | -- | --
> * `--health-interval` |   | Time between running the check (ms\|s\|m\|h) (default 0s)
> * `--health-retries` |   | Consecutive failures needed to report unhealthy
> * `--health-start-period` |   | Start period for the container to initialize before starting health-retries countdown (ms\|s\|m\|h) (default 0s)
> * `--health-timeout` |   | Maximum time to allow one check to run (ms\|s\|m\|h) (default 0s)

This can be useful for images that don't themselves implement the `HEALTHCHECk` instruction or for just altering the healthcheck of an existing image.

It looks like [the Docker Java client `com.github.dockerjava.api.model.HealthCheck` supports it](https://github.com/docker-java/docker-java/blob/c5c89327108abdc50aa41d7711d4743b8bac75fe/src/main/java/com/github/dockerjava/api/model/HealthCheck.java).

It would be useful to be able to leverage a wait strategy either at launch time or with something like `Wait.forCommand(...)`  that executes a command similar to how the Docker `HEALTHCHECK` instruction and `docker container run` CLI work.

**Comment by mkobit** [comment] 2019-09-02 16:01
I believe this shouldn't be marked as stale.

**Comment by rnorth** [comment] 2019-09-30 12:06
👍 sorry @mkobit, you're right that we should keep this open.

If anybody would like to contribute a PR for this we'd be very happy to review.

**Comment by glefloch** [comment] 2019-10-01 19:51
@rnorth, I would like to take this up. Regarding the implementation, would this take place in the `GenericContainer` class or as a `Wait` strategy like suggested by @mkobit ?

**Comment by rnorth** [comment] 2019-10-05 21:28
@glefloch sorry for the slow response. Please could you give me a little more time to think about this?

I’d like to be sure that we implement this because we need to, not just because we can. If we really are doing it to address a real need, the implementation probably varies according to the use cases.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glefloch** [comment] 2019-10-06 08:12
@rnorth, thanks for the answer. 

I actually started working on a basic implementation in the `Container` interface by adding this method:
`SELF withHealthCheck(HealthCheck healthCheck)` 
I can open a pull request so we can discuss about the implementation.

I still have some tests to write.

**Comment by kokosing** [comment] 2019-11-28 16:51
@glefloch Any update?

**Comment by bsideup** [comment] 2019-11-28 16:55
FYI there is `withCreateContainerCmdModifier` for anything that is not directly supported by `GenericContainer`:
```java
withCreateContainerCmdModifier(it -> {
    it.withHealthcheck(new HealthCheck().withTest(Arrays.asList("doCheck")));
})
```

**Comment by bsideup** [comment] 2019-12-01 15:45
Given my previous comment and as discussed in #2126, healthcheck is a bit too specific to have a first class support in `Container` interface. However, there is a not-so-difficult way of setting it with `withCreateContainerCmdModifier`, so I will close the issue :)

**Closed by bsideup** 2019-12-01 15:45 UTC
Labels: good first issue, hacktoberfest, help wanted

**Comment by henri-tremblay** [comment] 2023-02-18 15:05
I felt on this close issue but feels it could still be useful. I have a healthcheck in my dockerfile. And I want testcontainers to test if the container is healthy so I am testing my health command at the same time. The problem is that the interval is 30 seconds.  It's ok for a container in production but not for a test. However, my understanding is that if I add a new HealthCheck, it will replace the entire check on the container including the command to launch. If I do `getHealthCheck`, it returns null. Do we have a solution to that?
