### ISSUE TITLE
NetworkMode=host causes starting issue

### ISSUE THREAD

**Issue by rgugliel-da** [testcontainers/testcontainers-java#5151] opened 2022-03-04 13:46 UTC
I use the following code to start a container:
```
private class CustomOracleContainer
    extends GenericContainer[CustomOracleContainer](
      DockerImageName.parse("mycompany/oracle:enterprise-19.14.0-preloaded-20220120-27-36701e3")
    )

private val oracleContainer: CustomOracleContainer = new CustomOracleContainer()
  .withExposedPorts(1521)
  .withNetworkMode("host")
  .waitingFor(Wait.forLogMessage("DATABASE IS READY TO USE!\\n", 1))
  .withStartupTimeout(Duration.ofSeconds(160))
```

With testcontainers `1.15.1`, it works.
When updating to `1.16.3`, I get the following error:
```
ERROR ?.1.0-preloaded-20220120-27-36701e3] - Could not start container
org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Lambda expression in org.testcontainers.containers.GenericContainer: expected the predicate to return <true> but it returned <false> for input of <InspectContainerResponse(...))> within 5 seconds.
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:645)
```

Any idea what's happening ?

**Comment by kiview** [comment] 2022-03-08 14:57
I could confirm the issue and it might be the case for any container exposing ports.

**Comment by javahippie** [comment] 2022-06-20 16:18
I am also affected by this in a certain scenario. Is there any way I can help with this issue? (Information about the env, code, etc.?)

**Comment by kiview** [comment] 2022-06-20 19:48
I think we would need to debug why the check that was introduced with https://github.com/testcontainers/testcontainers-java/commit/034daa6e3d4a99c4ce71332ac49bf66957f903db (which did fix certain race condition scenarios, especially on Windows) seems to no apply if network mode is set to `host`.

**Comment by REslim30** [comment] 2022-08-20 02:52
Looking into this now. What I've found so far is:

`GenericContainer.start` waits for all the exposed ports to be available in the output of `docker inspect` as part of this snippet of code:

```
// Wait until inspect container returns the mapped ports
containerInfo =
  await()
    .atMost(5, TimeUnit.SECONDS)
    .pollInterval(DynamicPollInterval.ofMillis(50))
    .pollInSameThread()
    .until(
        () -> dockerClient.inspectContainerCmd(containerId).exec(),
        inspectContainerResponse -> {
            Set<Integer> exposedAndMappedPorts = inspectContainerResponse
                .getNetworkSettings()
                .getPorts()
                .getBindings()
                .entrySet()
                .stream()
                .filter(it -> Objects.nonNull(it.getValue())) // filter out exposed but not yet mapped
                .map(Entry::getKey)
                .map(ExposedPort::getPort)
                .collect(Collectors.toSet());
  
            return exposedAndMappedPorts.containsAll(exposedPorts);
        }
    );
```

The issue is, however, that published (exposed) ports are discarded on network mode `host`. E.g.

```
$ docker run --publish 8080:80 --network host --detach nginx
WARNING: Published ports are discarded when using host network mode
1da8e93a7de7011dff3a523e54d751de669988f8edcfea9f5c3c3cf54fefe0bc
```

In the above example the code expects `docker inspect` to return:
```
    {
        ...
        "NetworkSettings": {
           ...
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8080"
                    }
                ]
            }
        }
    }
```
But in reality, `docker inspect` returns:
```
    {
        ...
        "NetworkSettings": {
           ...
            "Ports": {}
        }
    }
```

So the container times out and throws an exception. From here, planning to look into the reasoning behind the above code snippet and potential fixes.

**Comment by kiview** [comment] 2022-08-22 12:34
@REslim30 If I remember correctly, parts of this code were refactored in order to remove certain race conditions on Docker Desktop (particularly Docker Desktop on Windows). Your findings make sense, this is likely the issue.

**Comment by REslim30** [comment] 2022-08-25 11:02
I've been testing locally on the code base and there's a simple fix we could do. We could add to `getMappedPort` an additional condition:

```
    default Integer getMappedPort(int originalPort) {
        ...
        Ports.Binding[] binding = new Ports.Binding[0];
        final InspectContainerResponse containerInfo = this.getContainerInfo();
        if (containerInfo != null) {
            if (containerInfo.getHostConfig().getNetworkMode().equals("host")) {
                return originalPort;
            }
            binding = containerInfo.getNetworkSettings().getPorts().getBindings().get(new ExposedPort(originalPort));
        }
        ...
    }
```
Which simply returns the original port if the container is in host mode. Though this feels a bit wrong. `host` mode doesn't really have a concept of mapped ports - the ports are simply on the host. It seems like we'd be stretching this method beyond it's original abstraction.

The more semantically correct alternative would be to throw if getMappedPort is called when container is host mode:
```
    default Integer getMappedPort(int originalPort) {
        ...
        Ports.Binding[] binding = new Ports.Binding[0];
        final InspectContainerResponse containerInfo = this.getContainerInfo();
        if (containerInfo != null) {
            if (containerInfo.getHostConfig().getNetworkMode().equals("host")) {
                throw new IllegalArgumentException("getMappedPort is not supported for host network mode");
            }
            binding = containerInfo.getNetworkSettings().getPorts().getBindings().get(new ExposedPort(originalPort));
        }
        ...
    }
```
We would, however, need to check all references to getMapped port and add in a check for host mode and there's a lot:
![Screenshot from 2022-08-25 20-27-41](https://user-images.githubusercontent.com/43259657/186647517-e42c85a3-fb84-46d6-83aa-006ff13323b5.png)

**Comment by kiview** [comment] 2022-08-25 12:53
Thanks for the investigation @REslim30, this is super helpful to proceed with this.

Both your points are valid and solution 1 seems very pragmatic. And we can improve on this by documenting this behavior in the Javadoc. The blast radius of solution 2 feels too high for me, to be really feasible. 

Before talking more about the potential solutions, I would like to circle back to understand the use cases for which to use a container with `host` network mode in the context of Testcontainers. Can you please give some context @rgugliel-da @javahippie?

**Comment by rgugliel-da** [comment] 2022-08-26 09:02
We need that as part of the quite specific pipeline.
We use Testcontainer to run an Oracle DB for testing on CI (Oracle enterprise). The reason we use Testcontainer and not directly the Oracle container is because of [technicalities of our CI platform](https://discuss.circleci.com/t/interacting-with-secondary-images/37315/3). This nesting of containers creates issue with queries issue to the DB except if we use network=nost.

**Comment by kiview** [comment] 2022-08-26 09:16
@rgugliel-da Thanks for sharing the context. So this is for solving an issue when using a containerized CI and you using Docker-Socket-Mounting to start sibling containers? 

I think I don't yet understand how the network setup affects querying the database in this case. Did you consider putting the sibling container on the same Docker network as the containerized test JVM and don't use dynamic port mapping at all, but rely on fixed port and Docker DNS?

**Comment by kiview** [comment] 2022-09-14 12:59
Hey @rgugliel-da, any chance to follow up on my previous question? Or alternatively @javahippie?

**Comment by rgugliel-da** [comment] 2022-09-14 13:15
Hi @kiview ,
I am very sorry for the delay in my response!

>  So this is for solving an issue when using a containerized CI and you using Docker-Socket-Mounting to start sibling containers?
That's correct.

> Did you consider putting the sibling container on the same Docker network as the containerized test JVM and don't use dynamic port mapping at all, but rely on fixed port and Docker DNS?
No, I did not. I went for the current approach because I thought I could use similar setup both locally and on CI.

**Comment by rgugliel-da** [comment] 2022-09-15 14:46
Situation A.
From the build container, I run my JVM (sbt) and from there I start a testcontainer running Oracle

**Comment by kiview** [comment] 2022-09-16 11:36
Thank you, then it seems we indeed need to support the network mode. I still don't understand why the Oracle container requires it in this setup, but since it worked in old Testcontainers versions we introduced a regression for this feature and I believe we should try to restore the fuctionality.

**Comment by REslim30** [comment] 2022-09-17 00:49
Sure, give me one sec.

**Comment by REslim30** [comment] 2022-09-17 02:13
@rgugliel-da, @javahippie @pretep22, can I confirm what environments you're on?

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

[Docker docs](https://docs.docker.com/network/host/)

I'm considering whether or not to throw an exception (or at least a warning) on non-linux environments when trying to use host mode.

**Comment by REslim30** [comment] 2022-09-17 06:53
Ok I've submitted a PR for this.

As for:
> I'm considering whether or not to throw an exception (or at least a warning) on non-linux environments when trying to use host mode.

I've added a separate issue for this. I think there's value in it. https://github.com/testcontainers/testcontainers-java/issues/5853

**Comment by rgugliel-da** [comment] 2022-09-19 05:15
> @rgugliel-da, @javahippie @pretep22, can I confirm what environments you're on?
> 
> > The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.
> 
> [Docker docs](https://docs.docker.com/network/host/)
> 
> I'm considering whether or not to throw an exception (or at least a warning) on non-linux environments when trying to use host mode.

I use Ubuntu.

**Comment by kiview** [comment] 2022-11-17 15:34
We close this as not planned, see comment in PR:
https://github.com/testcontainers/testcontainers-java/pull/5852#issuecomment-1318812304

> However, we don't want to support network mode host through Testcontainers, for 2 main reasons:
> 
> 1. Network mode host is only available on Linux (as also reflected in your implementation) and test code using it would therefore not be portable.
> 2. Containers started in network mode host share the same network namespace, which basically means they will use fixed ports. This is not aligned with the Testcontainers philosophy of avoiding test failures through port conflicts (meaning environment state).

**Closed by kiview** 2022-11-17 15:34 UTC
Labels: type/bug, resolution/acknowledged

**Comment by kiview** [comment] 2023-03-01 09:06
I'd like to clarify, network mode `host` still works as expected if not used in conjunction with `withExposedPorts()`. This also makes sense, because when using network mode `host`, there is no need to expose ports through the TC API, since the container is accessible through the host network.
