### ISSUE TITLE
Allow .testcontainers.properties from classpath

### ISSUE THREAD

**Issue by membersound** [testcontainers/testcontainers-java#3780] opened 2021-02-09 16:17 UTC
I would be great if `.testcontainers.properties` would be detected simply from classpath.

With that, the `reuse` option could be simply applied to all test databases at once.

It's somewhat problematic that the global reuse has to be enabled from *home* directory.
Because if one of my team mates checks out the project, it should be entirely configured, without having to read the some docs and eventually notice that everyone has to add his own `.testcontainers` property in his home path for getting the same test performance.

**Comment by bsideup** [comment] 2021-02-09 16:18
Duplicate of many reports, see the last answer in #3707.

**Closed by bsideup** 2021-02-09 16:18 UTC

**Comment by membersound** [comment] 2021-02-09 16:33
@bsideup how does your answer regarding `TESTCONTAINERS_RYUK_DISABLED` does have anything to do with my question about the `.testcontainers.properties` classpath file???

**Comment by bsideup** [comment] 2021-02-09 16:35
@membersound there are certain configuration options that are _per environment_, not _per project_.
Enabling reuse per project would also enable it on CIs. Most probably not something that you want.

See https://github.com/testcontainers/testcontainers-java/pull/1781#discussion_r369160221

**Comment by membersound** [comment] 2021-02-09 16:36
Well then probably the docs are wrong, which state it is actually possible?

https://www.testcontainers.org/features/configuration/

**Comment by bsideup** [comment] 2021-02-09 16:37
@membersound there is nothing wrong about it. Per-project configuration can be placed in `testcontainers.properties` file on classpath.

**Comment by membersound** [comment] 2021-02-09 17:02
Well but if I put `testcontainers.reuse.enable=true` into `/src/main/resources/testcontainers.properties` and enable reuse with `jdbc:tc:mariadb:10.5.8:///test?TC_REUSABLE=true`, I just get a warning the that reuse will not be enabled because it is missing in `~/.testcontainer.properties`. 

Doesn't that contradict it?

**Comment by bsideup** [comment] 2021-02-09 17:05
No, it does not, since `testcontainers.reuse.enable` is not a per-project configuration option, but per-environment.

**Comment by membersound** [comment] 2021-02-09 17:29
Okay, is there any overview which properties are per-project, and which are per-env?

**Comment by bsideup** [comment] 2021-02-09 21:18
@membersound `TestcontainersConfiguration` is the most up-to-date source of information:
https://github.com/testcontainers/testcontainers-java/blob/0e263f296556c2357f0d4ea99d120a3a2880ceb3/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L46

**Comment by membersound** [comment] 2021-02-10 08:00
You could maybe think about adding that to the docs explicit to directly gather which vars could be used from classpath.
I bet hardly anybody will look at the sourcecode in question...

**Comment by bsideup** [comment] 2021-02-10 09:17
@membersound the thing is, `checks.disable` and `testcontainers.reuse.enable` are two exceptions to the rule of "any var can be configured with the classpath file", as they are considered advanced optimization techniques (and reuse mode even being a preview feature, not a stable solution). When it comes to advanced stuff, some level of research is expected.

**Comment by frankiedrake** [comment] 2022-05-10 12:27
What about
`TestcontainersConfiguration.getInstance().updateUserConfig("testcontainers.reuse.enable", "true");`?

**Comment by frankiedrake** [comment] 2022-06-07 08:55
> > What about `TestcontainersConfiguration.getInstance().updateUserConfig("testcontainers.reuse.enable", "true");`?
> 
> Thank you so much. My team was ready to discontinue the use of TestContainers in favor of "old-school" compose files due to this issue and the configuration you provided helped me make it work.

I'm happy this workaround is useful for you!

**Comment by luispollo** [comment] 2023-08-21 22:48
I understand the motivations for closing this and other linked issues, but I just wanted to add that, in our case, we actually _want_ to enable container reuse both in local builds and in CI (our use case is to run DB migrations and some codegen that depends on those migrations in the same container), but as you might expect I don't (nor should I) have access to modifying that user-level file in the CI server, and so I'm stuck.

Personally, I think that it'd be great to give people the option to choose how they set this up. If they want to set it up at the project level, even if discouraged for the common case, why prevent them from doing so?
