### ISSUE TITLE
Second Testcontainer created after flyway was running ( using JDBC URL)

### ISSUE THREAD

**Issue by snap10** [testcontainers/testcontainers-java#4282] opened 2021-07-13 10:40 UTC
Hey, 
I configured my Postgres Testcontainer via the JDBC-URL feature so it's loaded automatically by Spring Boot 2.5 from the application.yml in the `test/resources/config/application.yaml` folder.

My overwrite in the `test/resources/config/application.yaml` is as follows.
```
spring:
  datasource:
    url: jdbc:tc:postgresql:12:///databasename
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
```
I'm seeing the strange behaviour, that a postgres container is successfully started, the migrations are applied. However then a second container is started which seems to be used for the tests which fail because the Tables are not present. Looking at the docker-environment it also seems that the first container is killed after the migrations are applied.

Tests are implemented using SPOCK

```
2:19:24.318 [Test worker] INFO  🐳 [postgres:12] - Creating container for image: postgres:12
12:19:24.364 [Test worker] INFO  🐳 [postgres:12] - Starting container with ID: ebdf4a0d3a87b07353102fe244a37262b350c2e3571569712b622908c0344171
12:19:24.863 [Test worker] INFO  🐳 [postgres:12] - Container postgres:12 is starting: ebdf4a0d3a87b07353102fe244a37262b350c2e3571569712b622908c0344171
12:19:25.835 [Test worker] INFO  🐳 [postgres:12] - Container postgres:12 started in PT1.537657S
12:19:25.929 [Test worker] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.11.1 by Redgate
12:19:25.930 [Test worker] INFO  o.f.c.i.d.base.BaseDatabaseType - Database: jdbc:postgresql://localhost:55047/test (PostgreSQL 12.7)
12:19:25.963 [Test worker] INFO  o.f.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.013s)
12:19:25.981 [Test worker] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "public"."flyway_schema_history" ...
12:19:26.008 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "public": << Empty Schema >>
12:19:26.017 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "public" to version "0.001 - initialize"
12:19:26.047 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Successfully applied 1 migration to schema "public", now at version v0.001 (execution time 00:00.046s)
12:19:26.428 [Test worker] WARN  com.zaxxer.hikari.HikariConfig - Pool - idleTimeout has been set but has no effect because the pool is operating as a fixed size pool.
12:19:26.428 [Test worker] INFO  com.zaxxer.hikari.HikariDataSource - Pool - Starting...
12:19:26.436 [Test worker] INFO  🐳 [postgres:12] - Creating container for image: postgres:12
12:19:26.482 [Test worker] INFO  🐳 [postgres:12] - Starting container with ID: 1674a95e7c494055214f6f53295ac7e3d0a2baa6211d1df20651a2f6ab85a1c2
12:19:26.954 [Test worker] INFO  🐳 [postgres:12] - Container postgres:12 is starting: 1674a95e7c494055214f6f53295ac7e3d0a2baa6211d1df20651a2f6ab85a1c2
12:19:27.862 [Test worker] INFO  🐳 [postgres:12] - Container postgres:12 started in PT1.42629S
12:19:27.886 [Test worker] INFO  com.zaxxer.hikari.HikariDataSource - Pool - Start completed.
```

Does anyone have an idea what might be wrong here?

**Comment by yerzhant** [comment] 2021-09-21 11:29
I have the same issue.

With this setup:
```
spring:
  r2dbc:
    url: r2dbc:tc:postgresql:///test?TC_IMAGE_TAG=11-alpine
  flyway:
    url: jdbc:tc:postgresql:11-alpine:///test
```
The first container (for migrations) just gets down and a new one is created anew (for tests).

I had the same issue with in-mem H2 which was resolved by adding DB_CLOSE_DELAY=-1 parameter:
```
spring:
  r2dbc:
    url: r2dbc:h2:mem:///test;MODE=PostgreSQL
  flyway:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
```

I couldn't find a parameter for Postgres driver to prohibit closing a connection (pool).

**Comment by mn7z** [comment] 2023-01-06 14:55
I had similar issue, @snap10 @yerzhant . My use case required:
* separate user for doing migrations
* separate user for the app

My approach was to:
1. manually start the postgresql container instead of relying on the convenient ":tc:" in url
2. have an init script for other user
3. use @DynamicPropertySource to override base datasource & flyway datasource.

The the pseudo code below for the rough idea:

`init.sql` (sitting around in the classpath);
```sql
create user app_user with password 'app_user';
grant connect on database app_database_test to app_user;
```

```java
@Container
static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(DockerImageName.parse("postgres:14"))
      .withUsername("admin_user")
      .withPassword("admin_password")
      .withDatabaseName("app_database_test")
      .withInitScript("init.sql"); // initsql from above

@DynamicPropertySource
  static void properties(DynamicPropertyRegistry registry) {
    postgres.start();
    // instructing default connection to use app_user from init.sql
    registry.add("spring.datasource.url", () -> String.format("jdbc:postgresql://localhost:%d/app_database_test", postgres.getFirstMappedPort()));
    registry.add("spring.datasource.username", () -> "app_user");
    registry.add("spring.datasource.password", () -> "app_user");
    // instructing flyway to use admin user
    registry.add("spring.flyway.url", () -> String.format("jdbc:postgresql://localhost:%d/app_database_test", postgres.getFirstMappedPort()));
    registry.add("spring.flyway.user", () -> "admin_user");
    registry.add("spring.flyway.password", () -> "admin_password");
  }
```

This way only single postgres container is started as I had exactly the same problem - 1 container started and migrated everything, then second started and did not have anything in it. 

If you do find a more elegant solution please let me know.

**Comment by eddumelendez** [comment] 2023-01-07 06:00
I think we have different issues here

@snap10 by any chance, do you have `spring.flyway.url` with value `jdbc:tc:postgresql:12:///databasename`? If so, you only need the `spring.datasource.url` and if flyway deps are in the classpath it will be auto-configured. spring boot's flyway auto-configuration can use an existing datasource or create a new one if `spring.flyway.url` is set. For that reason, you can experience the issue.

@yerzhant your case is very similar but in this case I would suggest to use PostgreSQLContainer and set the properties via `@DynamicPropertiySource`. See an example [here](https://github.com/eddumelendez/testcontainers-samples/blob/main/spring-boot-r2dbc-postgresql-chaos/src/test/java/com/example/springbootr2dbcpostgresqlchaos/SpringBootR2dbcPostgresqlChaosApplicationTests.java#L40-L52)

@mn7z following the code you shared I can say the issue is totally different and you need to grant permissions to the new database user. Adding the following code should fix it

```java
@BeforeEach
void setup() {
	try {
//		postgres.execInContainer("psql", "-U", "admin_user", "-d", "app_database_test", "-c", "grant all privileges on table profile to app_user");
		postgres.execInContainer("psql", "-U", "admin_user", "-d", "app_database_test", "-c", "grant select on all tables in schema public to app_user");
	} catch (IOException e) {
		throw new RuntimeException(e);
	} catch (InterruptedException e) {
		throw new RuntimeException(e);
	}
}
```

If you continue having issues please submit a minimal project which reproduce the issue.

**Comment by mn7z** [comment] 2023-01-07 19:16
@eddumelendez thank you for reply. I think I might have been misunderstood - my examples posted _is actual solution to the problem_.

My problem was then when I had such configuration in `application.yml` (tests) spring boot:

```
spring:
  flyway:
    url: jdbc:tc:postgresql:///app_database_test?TC_INITSCRIPT=init.sql
    user: admin_user
    password: admin_user
  datasource:
      url: jdbc:tc:postgresql:///app_database_test
      username: app_user
      password: app_user
```

Then the application during startup would:
1. start the flyway postgresql container 
2. migrate the schema
3. end
4. start separate postgresql container
5. -no schema present-

So my above comment was really just my take how did overcome this.

**Comment by eddumelendez** [comment] 2023-01-09 19:33
@mn7z thanks to clarify! I though something was missing so just complement the answer by grant permission.

**Comment by eddumelendez** [comment] 2023-02-10 23:40
Answers to the original question were provided already and there is no reply back. @snap10 feel free to reopen if those doesn't work for you.

**Closed by eddumelendez** 2023-02-10 23:40 UTC
