### ISSUE TITLE
Custom MySQL Container issue starting docker image

### ISSUE THREAD

**Issue by DPetrunov** [testcontainers/testcontainers-java#458] opened 2017-09-20 12:21 UTC
Hello,

I'm trying to use TestContainers with Spring Boot 1.5.7 but I have a problem starting up a custom db container.

Because there is currently no way to customize the MySQLContainer class, I decided to write one on my own. It's basically the same as the one in the MySQL module of test containers, except I made it using custom username/password/dbname. I'll provide the implementation if neccessary, but I don't think the problem is there.

Using a test profile config file I have a pretty standard datasource configuration:

```
datasource:
              url: jdbc:tc:mysql://localhost:3306/apiAsyncDB
              username: root
              password: password
              driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

```

I register it to the ServiceProvider discovery like this:

```
@AutoService(JdbcDatabaseContainerProvider.class)
public class CustomMySQLContainerProvider extends JdbcDatabaseContainerProvider {

    @Override
    public boolean supports(String databaseType) {
        return databaseType.equals(CustomMySQLContainer.NAME);
    }

    @Override
    public JdbcDatabaseContainer newInstance(String tag) {

        return new CustomMySQLContainer(CustomMySQLContainer.IMAGE + ":" + tag);
    }
}
```

When debugging the **org.testcontainers.jdbc.ContainerDatabaseDriver** I can see that it finds my custom container and loads it, so that's not the issue either.

However when I start the test that I'm trying to run i get the following error output:

`15:08:34.258 [main] ERROR 🐳 [mysql:latest] - Container log output (if any) will follow:
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDOUT: Initializing database
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.366302Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.368458Z 0 [Warning] One can only use the --user switch if running as root
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.526213Z 0 [Warning] InnoDB: New log files created, LSN=45790
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.932390Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.991050Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 25d1b97c-9dfc-11e7-8a20-0242ac110002.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.994309Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:34.995111Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164499Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164550Z 1 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164565Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164590Z 1 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.265 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164774Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.164914Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.165329Z 1 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:36.165362Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDOUT: Database initialized
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDOUT: Initializing certificates
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Generating a 2048 bit RSA private key
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ......+++
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ................................................+++
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: unable to write 'random state'
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: writing new private key to 'ca-key.pem'
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: -----
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Generating a 2048 bit RSA private key
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ..................+++
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: .....................................................+++
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: unable to write 'random state'
15:08:34.266 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: writing new private key to 'server-key.pem'
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: -----
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Generating a 2048 bit RSA private key
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ...........................+++
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ..........+++
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: unable to write 'random state'
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: writing new private key to 'client-key.pem'
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: -----
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDOUT: Certificates initialized
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDOUT: MySQL init process in progress...
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.774360Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.775753Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 90 ...
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.778228Z 0 [Warning] One can only use the --user switch if running as root
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 
15:08:34.267 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779800Z 0 [Note] InnoDB: PUNCH HOLE support available
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779921Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779933Z 0 [Note] InnoDB: Uses event mutexes
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779941Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779948Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.779955Z 0 [Note] InnoDB: Using Linux native AIO
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.780570Z 0 [Note] InnoDB: Number of pools: 1
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.780835Z 0 [Note] InnoDB: Using CPU crc32 instructions
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.784445Z 0 [Note] InnoDB: Initializing buffer pool, total size = 16M, instances = 1, chunk size = 16M
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.789273Z 0 [Note] InnoDB: Completed initialization of buffer pool
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.790302Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
15:08:34.268 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.802305Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.810204Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.810290Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.879686Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.881742Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.881824Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.882791Z 0 [Note] InnoDB: Waiting for purge to start
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.933073Z 0 [Note] InnoDB: 5.7.19 started; log sequence number 2539322
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.933423Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.934090Z 0 [Note] Plugin 'FEDERATED' is disabled.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.934707Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170920 12:06:38
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.940565Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.940934Z 0 [Warning] CA certificate ca.pem is self signed.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.944868Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.944954Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.944979Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.945031Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.945062Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.269 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.945078Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.946444Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.946460Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.953280Z 0 [Note] Event Scheduler: Loaded 0 events
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.953594Z 0 [Note] mysqld: ready for connections.
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Version: '5.7.19'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.953627Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check.
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.953633Z 0 [Note] Beginning of list of non-natively partitioned tables
15:08:34.270 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:38.962449Z 0 [Note] End of list of non-natively partitioned tables
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194114Z 5 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194170Z 5 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194197Z 5 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194205Z 5 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194216Z 5 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194586Z 5 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: 2017-09-20T12:06:42.194655Z 5 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: mysql: [Warning] Using a password on the command line interface can be insecure.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: mysql: [Warning] Using a password on the command line interface can be insecure.
15:08:34.271 [dockerjava-netty-1-3] INFO  🐳 [mysql:latest] - STDERR: ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'`

Is this some misconfiguration of the **my.cnf** file or is something else going wrong?

I'm running Docker Version 17.06.2-ce-mac27 (19124) on OSX Sierra 10.12.6 (16G29)

Any help would be greatly appreciated.

**Comment by rnorth** [comment] 2017-09-20 18:54
Hi @DPetrunov 
I'm not sure, but please could you show your custom container implementation, including what the base image is called and how you're passing through the username/password etc?

Base on the error `ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'` my feeling is that this is something internal rather than anything testcontainers is causing, but perhaps getting more eyes on it would be a good thing.

Richard

**Comment by DPetrunov** [comment] 2017-09-20 19:26
Hey @rnorth 
Here's the implementation of my custom class:

```
public class CustomMySQLContainer<SELF extends CustomMySQLContainer<SELF>> extends JdbcDatabaseContainer<SELF> {

    private static final String MY_CNF_CONFIG_OVERRIDE_PARAM_NAME = "TC_MY_CNF";

    private String databaseName = "test";
    private String username = "test";
    private String password = "test";
    private String rootPassword = "test";
    private String driver = "com.mysql.cj.jdbc.Driver";

    public static final String NAME = "mysql";
    public static final String IMAGE = "mysql";
    public static final Integer MYSQL_PORT = 3306;

    public CustomMySQLContainer() {

        super(IMAGE + ":latest");
    }

    public CustomMySQLContainer(String dockerImageName) {

        super(dockerImageName);
    }

    @Override
    protected Integer getLivenessCheckPort() {

        return getMappedPort(MYSQL_PORT);
    }

    @Override
    protected void configure() {

        optionallyMapResourceParameterAsVolume(MY_CNF_CONFIG_OVERRIDE_PARAM_NAME, "/etc/mysql/conf.d", "mysql-default-conf");

        addExposedPort(3306);

        addEnv("MYSQL_DATABASE", databaseName);
        addEnv("MYSQL_USER", username);
        addEnv("MYSQL_PASSWORD", password);
        addEnv("MYSQL_ROOT_PASSWORD", rootPassword);

        setCommand("mysqld");

        setStartupAttempts(3);
    }

    @Override
    public String getDriverClassName() {

        return driver;
    }

    @Override
    public String getJdbcUrl() {

        return "jdbc:mysql://" + getContainerIpAddress() + ":" + getMappedPort(MYSQL_PORT) + "/" + databaseName;
    }

    @Override
    public String getUsername() {

        return username;
    }

    @Override
    public String getPassword() {

        return password;
    }

    @Override
    public String getTestQueryString() {

        return "SELECT 1";
    }

    public SELF withConfigurationOverride(String s) {

        parameters.put(MY_CNF_CONFIG_OVERRIDE_PARAM_NAME, s);
        return self();
    }

    public SELF withDatabaseName(final String databaseName) {

        this.databaseName = databaseName;
        return self();
    }

    public SELF withUsername(final String username) {

        this.username = username;
        return self();
    }

    public SELF withPassword(final String password) {

        this.password = password;
        return self();
    }

    public SELF withDriver(final String driver) {

        this.driver = driver;
        return self();
    }
}
```

As you can see I really only added the option to set the MySQL driver class as the one used in the default implementation is deprecated. I see now that you actually committed a change that will allow for  a more customizable configuration of the DB modules in a future release, but I would really like to find out why mine fails.

And here's how i construct my object:

```
@ClassRule
CustomMySQLContainer customMySQLContainer = new CustomMySQLContainer()
                .withDatabaseName("apiAsyncDB")
                .withUsername("root")
                .withPassword("password");
```
As for the image it's always downloading the latest.

DPetrunov

**Comment by iNikem** [comment] 2018-01-25 08:01
@DPetrunov @rnorth As testcontainers now allow customisation of db containers out of the box, may be this issue can be closed as not relevant anymore?

**Comment by kiview** [comment] 2018-01-25 09:15
I'll close this for now, since @iNikem is right regarding the root cause of this problem and this issue if more about some specific implementation problems of a custom, user-written, class.

@DPetrunov Please let us know, if you think we need to re-open this issue.

**Closed by kiview** 2018-01-25 09:15 UTC

**Comment by DPetrunov** [comment] 2018-01-25 09:28
Hey guys, I think its fine to close it for now.

**Comment by bojanv55** [comment] 2018-10-26 08:12
Had same problem. Just had to remove withUsername since root user is already present in mysql...

> @ClassRule
> CustomMySQLContainer customMySQLContainer = new CustomMySQLContainer()
>                 .withDatabaseName("apiAsyncDB")
>                 .withUsername("root") <--- tries to create user "root" in db, when you already have this username by default
>                 .withPassword("password");
