### ISSUE TITLE
Move junit4 support to an another artifact

### ISSUE THREAD

**Issue by remal** [testcontainers/testcontainers-java#1525] opened 2019-06-03 16:21 UTC
Currently Testcontainers project (for example `org.testcontainers:testcontainers:1.11.3` artifact) depends on JUnit4 library. This dependency is not optional. But I don't use JUnit4 in my project and would like not to have it on dependencies list.

Please move JUnit4 support in another artifact like it's done in JUnit5 case.

**Comment by wilkinsona** [comment] 2019-06-04 11:30
I'm in the process of moving all of Spring Boot's tests to JUnit 5 and I'd really like to see this too. Having `org.junit.Test` and friends on the classpath makes for an awkward developer experience when trying to exclusively use the Jupiter API.

**Comment by campa** [comment] 2019-06-12 14:29
Same request here, thanks in advance.
Great Lib thanks !!

**Comment by rnorth** [comment] 2019-06-12 19:27
This is actually a duplicate of #87, one of our oldest open tickets.

The short story is that this is definitely something we have wanted to do for a long time. There will be breaking changes associated with it, so we need to time it and do it carefully. I'd expect this to be something that happens before Q3, but wouldn't want to commit to a timescale fully just yet.

I'll close this as a duplicate of #87 - please vote for and follow that issue!
Thanks @remal, @wilkinsona, @campa and @tisoft for your encouragement to tackle this.

**Closed by rnorth** 2019-06-12 19:27 UTC
