### ISSUE TITLE
Problems with TestContainers and Kotlin

### ISSUE THREAD

**Issue by iirekm** [testcontainers/testcontainers-java#318] opened 2017-03-31 09:32 UTC
TestContainers depends on construction of raw types and pattern like `class C<SELF extends C<SELF>>`. Unfortunately Kotlin, and probably other JVM languages don't like it - see https://youtrack.jetbrains.com/issue/KT-17186

Adding static factory methods could solve those problems.

**Comment by martin-g** [comment] 2017-03-31 11:54
My workaround is:
```kotlin
class KGenericContainer(imageName: String) : GenericContainer<KGenericContainer>(imageName)
```
charming, isn't it ? :-)

**Comment by rnorth** [comment] 2017-04-01 17:09
Yeah, I'd not appreciated this would be a problem with Kotlin but it's unfortunate :(
@bsideup, something to consider for the next version...

**Comment by asafm** [comment] 2017-04-01 21:43
Just reading this generic expression gives you a headache :)

**Comment by mpecan** [comment] 2017-07-18 11:37
This is related directly to #238 and can be resolved in the way that was suggested by @bsideup (https://github.com/testcontainers/testcontainers-java/issues/238#issuecomment-256258802).

**Comment by mkobit** [comment] 2018-05-16 19:35
Another ugly way to handle this as described in the [YouTrack issue](https://youtrack.jetbrains.com/issue/KT-17186):

```kotlin
val container: GenericContainer<*> = GenericContainer<Nothing>()
```

**Comment by helmbold** [comment] 2018-05-29 08:03
@mkobit [Method chaining as shown in the docs](https://www.testcontainers.org/usage/generic_containers.html#example) is not possible with your approach ( `GenericContainer<Nothing>()`). 

I suggest to use the [workaround](https://github.com/testcontainers/testcontainers-java/issues/318#issuecomment-290692749) from @martin-g instead.

**Comment by kiview** [comment] 2018-10-11 10:11
First time I tried to use Testcontainers with Kotlin and ran into exactly this problem, so great it found the workarounds here :sweat_smile:

**Comment by alex0ptr** [comment] 2019-10-10 21:01
@helmbold Chaining is easily possible with Kotlin native scoping functions, example:

```kotlin
val container: GenericContainer<*> = GenericContainer<Nothing>()
                                        .apply{ withExposedPorts(6379) }
```

I'll make a merge request to propose this in the Kotlin Examples.

**Comment by xyzwps** [comment] 2019-10-29 03:55
I created a sub class of MySQLContainer:

```kt
internal class SpecifiedMySQLContainer(val image: String) : MySQLContainer<SpecifiedMySQLContainer>(image)

val mysqlContainer = SpecifiedMySQLContainer(image = "mysql:5.7.28")
                .withDatabaseName("dbname")
```

**Comment by thaibt** [comment] 2021-04-23 22:17
> Another ugly way to handle this as described in the [YouTrack issue](https://youtrack.jetbrains.com/issue/KT-17186):
> 
> ```kotlin
> val container: GenericContainer<*> = GenericContainer<Nothing>()
> ```

This saved my life... Was to frustrated and I did not find this thread.

**Comment by sdeleuze** [comment] 2021-12-28 12:33
Please close this issue as Kotlin 1.6 which fixes it has been released.

**Comment by bsideup** [comment] 2021-12-28 12:35
@sdeleuze good point!
It is great to see Kotlin supporting more and more "in the wild" cases 🎉 
IIRC some Spring's builders also benefited from it? Double win!

**Closed by bsideup** 2021-12-28 12:35 UTC
Labels: type/feature, resolution/acknowledged

**Comment by sdeleuze** [comment] 2021-12-28 14:09
Yep indeed that fixed a few Spring builder APIs as well. I am glad the Kotlin team has listened feedback from the community to fix this really annoying issue.

**Comment by asomov** [comment] 2025-02-27 12:55
Unfortunately, the issue is not completely solved in Kotlin 2. 
The `GenericContainer` still requires `Nothing` to be used.

**Comment by sdeleuze** [comment] 2025-03-12 15:41
@asomov I just tried `val container: GenericContainer<*> = GenericContainer("someImage")` with Kotlin `2.1.10` and it seems to work as expected. If you manage to reproduce, could you please share a repro?

**Comment by asomov** [comment] 2025-03-13 05:19
@sdeleuze Unfortinately, after unsuccessful attempt to use testcontainers, the approach was stopped. Reproducing the use case would be a major activity. 
I agree, that my setup might be not properly configured (and that is why it did not work)
I will drop my above comment to avoid any misunderstand for the community.
Thank you!
