### ISSUE TITLE
[Bug]: ScriptUtils.splitSqlScript works incorrectly with statements containing IFs and LOOPs

### ISSUE THREAD

**Issue by inponomarev** [testcontainers/testcontainers-java#7647] opened 2023-10-10 20:30 UTC
### Module

Core

### Testcontainers version

1.19.1

### Using the latest Testcontainers version?

Yes

### Host OS

not relevant

### Host Arch

not relevant

### Docker version

```shell
not relevant
```

### What happened?

Current version of `ScriptUtils.splitSqlScript` tries to take into account `BEGIN...END` blocks. However, it treats any `END` as an end of the block, even if it's `END IF` or `END LOOP`, so that the following one-statement script

```sql
BEGIN
     rec_loop: LOOP
         FETCH blah;
         IF something_wrong THEN LEAVE rec_loop; END IF;
         do_something_else;
     END LOOP;
END;
```

Is incorrectly  split into following "statements":

```sql 
BEGIN
    rec_loop: LOOP
        FETCH blah;
        IF something_wrong THEN LEAVE rec_loop; END IF
-----------------------------------------------------------------
       do_something_else
-----------------------------------------------------------------
   END LOOP
-----------------------------------------------------------------
END
```

This is also broken for the case when a special statement separator is used (like `GO` in MSSQL tradition, `/` in Oracle tradition or `@` in DB2).

The following statement is not split over `@` sign as when it comes to the separator, the algorithm counted more `END`s than `BEGIN`s and and since the balance is not zero, it is not splitting the code:

```sql
BEGIN
    rec_loop: LOOP
        FETCH blah;
        IF something_wrong THEN LEAVE rec_loop; END IF;
        do_something_else;
    END LOOP;
END;
@
CALL something();
@
```

**Comment by eddumelendez** [comment] 2023-10-10 20:32
Hi @inponomarev, please consider reading our [Contributing guideline](https://java.testcontainers.org/contributing/) and the form before raising a PR and then and issue.

> Thanks for taking the time to fill out this bug report! Before submitting a bug, please make sure there is no existing issue for the one you encountered and it has been discussed with the team via [discussions](https://github.com/testcontainers/testcontainers-java/discussions) or Slack.

Closing this as duplicate of #7646

**Closed by eddumelendez** 2023-10-10 20:32 UTC
Labels: type/bug
