### ISSUE TITLE
Containers reconnect

### ISSUE THREAD

**Issue by augi** [testcontainers/testcontainers-java#1605] opened 2019-07-12 10:13 UTC
[Docker Compose Gradle plugin](https://github.com/avast/gradle-docker-compose-plugin) (I'm the author) has a nice feature of reconnecting to already running containers. It's very useful when iterating over an integration test because e.g. RabbitMQ Windows Container is starting few minutes and you don't want to wait for the container start again and again.

How it could work in TestContainers:
* When creating a new container, add an unique label that indicates why the container is being started, e.g. full test (suite) name.
  * If there is already a container with this label, don't create a new container, just perform the waiting policy instead.
* When a container should be removed, no action is performed (so the container is still running). Or alternatively, the container is just paused/stopped.

Obviously, this shouldn't be the default behavior. It would be fine if this behavior could be enabled using an environment variable, or using a properties files.

If this feature request makes sense for you, could you please point me to the right direction how to implement this feature (where to start) ?

Thanks!

**Comment by bsideup** [comment] 2019-07-12 10:17
Duplicate of #781 (see the answers/progress there)

**Closed by bsideup** 2019-07-12 10:17 UTC
