### ISSUE TITLE
'dockerHost' ignored on 'EnvironmentAndSystemPropertyClientProviderStrategy'

### ISSUE THREAD

**Issue by hdimitriou** [testcontainers/testcontainers-java#854] opened 2018-09-03 16:43 UTC
I am working on a system with multiple different docker sockets for user isolation and I noticed that testcontainers does not work with socket different than /var/run/docker.sock

I did 
`DOCKER_HOST=unix:///var/run/docker-ciiiiii.sock gradlew ...{code}` on my project that uses testcontainers and I got

`09:31:58.666 [Test worker] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved:
        dockerHost=unix:///var/run/docker-ciiiiii.sock
....`

and then it connected even though there's no such socket
`    09:31:58.671 [Test worker] INFO org.testcontainers.DockerClientFactory - Docker host IP address is localhost
    09:31:58.677 [Test worker] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.exec.InfoCmdExec@3ba3ce8
    09:31:59.145 [Test worker] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.exec.VersionCmdExec@22828e43
    09:31:59.162 [Test worker] INFO org.testcontainers.DockerClientFactory - Connected to docker:`

I would expect EnvironmentAndSystemPropertyClientProviderStrategy to fail if supplied a wrong socket and to respect the actual socket when it's valid. 
On an environment that is using another socket and does not have access to /var/run/docker.sock I get the printout with the proper socket but then I get an exception
`        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: org.testcontainers.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Permission denied: /var/run/docker.sock
        at org.testcontainers.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:107)`

It feels like the actual ping command is hardcoded to point to the default docker socket.

**Comment by bsideup** [comment] 2018-09-03 20:02
Hi @hdimitriou,

By default, Testcontainers will try different strategies to resolve Docker environment.
As you can see from the logs, it fails to find an env with `/var/run/docker-ciiiiii.sock` and continued with `UnixSocketClientProviderStrategy`

**Comment by hdimitriou** [comment] 2018-09-04 08:31
It does not matter how many strategies it attempts. I have it configured to work via environment variables and any other strategy will fail by default. The point is that the strategy that looks up the environment variables should pick up the different docker host variable and use it

**Comment by bsideup** [comment] 2018-09-04 08:33
@hdimitriou and it does :) But there is another one, `UnixSocketClientProviderStrategy`:
https://github.com/testcontainers/testcontainers-java/blob/f928c4d7e307f765a4bb97df620db30e83bbd245/core/src/main/java/org/testcontainers/dockerclient/UnixSocketClientProviderStrategy.java

**Comment by hdimitriou** [comment] 2018-09-04 08:42
But the socket there is hardcoded right?
`protected static final String DOCKER_SOCK_PATH = "/var/run/docker.sock";`

**Comment by aantoniadisatypon** [comment] 2018-09-04 13:33
I believe that the problem is that in [TestcontainersDockerCmdExecFactory.UnixDomainSocketInitializer#connect](https://github.com/testcontainers/testcontainers-java/blob/d2ff0730eaafcf45076fe8a8d4a760a10c8b0b58/core/src/main/java/org/testcontainers/dockerclient/transport/TestcontainersDockerCmdExecFactory.java#L162) method is using a hardcoded value for the socketPath (which is`/var/run/docker.sock`) instead of the one given in the configuration. 

It also seems that `dockerClientConfig` is not used by UnixDomainSocketInitializer, which is the choice for unix schema.

**Comment by kiview** [comment] 2018-10-01 11:52
Pending PR to fix this completely is #862

**Comment by bsideup** [comment] 2019-07-10 07:01
@usmanovbf 
#855 is already merged. Are you sure that you're hitting the same issue?

**Comment by usmanovbf** [comment] 2019-08-21 22:21
@bsideup You did it only for Netty but not for okhttp. Same error occurs when after correct setting of environment variable `DOCKER_HOST` here https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L159 wrong default value will be assigned here https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/UnixSocketClientProviderStrategy.java#L36

**Comment by rnorth** [comment] 2021-06-09 09:21
Closing as this was made obsolete in #4118

**Closed by rnorth** 2021-06-09 09:21 UTC
Labels: resolution/acknowledged, type/bug, type/question
