### ISSUE TITLE
Set junit-jupiter as default core implementation

### ISSUE THREAD

**Issue by altro3** [testcontainers/testcontainers-java#5404] opened 2022-05-31 21:28 UTC
Maybe it's time to move to junit5 as default? Junit5 exists 5 years and I think all new projects use this particular library, not the outdated junit4. The problem is that it's not possible to remove junit4 from classpath at the moment because testcontainers uses it in the core module :-(

**Comment by norrs** [comment] 2022-08-02 20:51
@skotsj This ridiculously hack actually works. Thanks for sharing, as this is way better than having Junit4 and vintage engine loaded in Junit5.

**Comment by kiview** [comment] 2022-08-09 09:39
Thanks for sharing the workaround @skotsj. We have plans to remove the JUnit4 dependency in the core. However, we will completely remove any test framework dependency in the core and not replace it with the JUnit Jupiter one.

I'll close this issue as a duplicate of #970.

**Closed by kiview** 2022-08-09 09:39 UTC
