### ISSUE TITLE
testcontainer.properties isn't honored if placed in java classpath 

### ISSUE THREAD

**Issue by pluong** [testcontainers/testcontainers-java#3832] opened 2021-02-24 17:04 UTC
For java development, if placing testcontainer.properties in classpath (for instance in the resource folder), those properties, particularly the startup check properties aren't being read during startup of the tests.  For example, if a testcontainer.properties file which had `checks.disable=true` was placed in the classpath, that property wouldn't be read or considered when a unit test involving testcontainers is started.

**Comment by bsideup** [comment] 2021-02-24 19:11
Duplicate of #3780

**Closed by bsideup** 2021-02-24 19:11 UTC
