### ISSUE TITLE
`confluentinc/cp-kafka:6.2.2` and `7.0.1` don't work with `KafkaContainer`

### ISSUE THREAD

**Issue by kiview** [testcontainers/testcontainers-java#4781] opened 2021-12-13 17:01 UTC
This issue has been originally reported by @simonbasle in our Testcontianers Slack.

While we initially thought this is related to GitHub Actions, it seems this is a general incompatibility of `KafkaContainer` with `cp-kafka` images >= `6.2.2`. 

During container startup, our `InternalCommandPortListeningCheck` will fail with logs along the lines of:
```
17:57:13.528 WARN  org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck - An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection to 127.0.0.1 failed: Connection refused.
Ncat: Trying next address...
Ncat: Cannot assign requested address.
/bin/bash: connect: Cannot assign requested address
/bin/bash: /dev/tcp/localhost/9093: Cannot assign requested address
```

Subsequently, our `exec` is failing:
```
17:57:13.532 INFO  🐳 [confluentinc/cp-kafka:6.2.2] - Container confluentinc/cp-kafka:6.2.2 started in PT2.1713743S
17:57:13.532 DEBUG org.testcontainers.containers.ExecInContainerPattern - /hungry_newton: Running "exec" command: kafka-configs --alter --bootstrap-server BROKER://994010ec6ac8:9092 --entity-type brokers --entity-name 1 --add-config advertised.listeners=[PLAINTEXT://127.0.0.1:62036,BROKER://994010ec6ac8:9092]
17:57:13.669 ERROR 🐳 [confluentinc/cp-kafka:6.2.2] - Could not start container
com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"Container 994010ec6ac8c3cb2ff554a849fdba13b8e38ec6798585d648a766b601fbfd6c is not running"}
```

**Comment by simonbasle** [comment] 2021-12-13 17:09
Thanks for your help in debugging this @kiview !

On a side note, about the `Ncat` log, there is still some such logs visible if you enable trace logging, even with `6.2.1`... That's because of some polling aspect, I'm assuming.

So right after these logs, we get a success with 6.2.1:
```
    /bin/bash: connect: Cannot assign requested address
    /bin/bash: /dev/tcp/localhost/9093: Cannot assign requested address

    [2021-12-13 12:57:56,321] [testcontainers-wait-0] [org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck] TRACE Check for [9093, 2181] took PT8.449S. Result code '0', stdout message: '/proc/net/tcp:   3: 00000000:2385 00000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 36725 1 0000000000000000 100 0 0 10 0                     
    /proc/net/tcp:   4: 00000000:0885 00000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 36445 1 0000000000000000 100 0 0 10 0                     
    /proc/net/tcp:   5: 0100007F:AC38 0100007F:0885 01 00000000:00000000 00:00000000 00000000  1000        0 36641 1 0000000000000000 20 4 10 10 -1                    
    /proc/net/tcp:   6: 0100007F:0885 0100007F:AC38 01 00000000:00000000 00:00000000 00000000  1000        0 36642 1 0000000000000000 20 4 21 10 -1       
```
But with 6.2.2 we get an error:
```
     [2021-12-13 12:19:46,251] [testcontainers-wait-0] [org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck] TRACE Check for [9093, 2181] took PT3.331S. Result code '137', stdout message: ''
    [2021-12-13 12:19:46,251] [testcontainers-wait-0] [org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck] WARN An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, 
```

**Comment by sergey-morenets** [comment] 2022-05-15 10:00
Hi

Confirmed that TestContainers 16.3 fails to start even GenericContainer for cp-kafka:7.1.1:

```
		kafka = new GenericContainer<>(DockerImageName.parse("confluentinc/cp-kafka:7.1.1"))
				.withEnv("KAFKA_PROCESS_ROLES", "broker,controller").withEnv("KAFKA_NODE_ID", "1")
				.withEnv("KAFKA_LISTENER_SECURITY_PROTOCOL_MAP", "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT")
				.withEnv("KAFKA_ADVERTISED_LISTENERS", "PLAINTEXT://kafka:9092")
				.withEnv("KAFKA_CONTROLLER_QUORUM_VOTERS", "1@kafka:9093")
				.withEnv("KAFKA_LISTENERS", "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093")
				.withEnv("KAFKA_CONTROLLER_LISTENER_NAMES", "CONTROLLER")
				.withExposedPorts(9092);
```

Log output:

```
[testcontainers-wait-0] WARN org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck - An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection to 127.0.0.1 failed: Connection refused.
Ncat: Trying next address...
Ncat: Cannot assign requested address.
/bin/bash: connect: Cannot assign requested address
/bin/bash: /dev/tcp/localhost/9092: Cannot assign requested address
)
[main] INFO 🐳 [confluentinc/cp-kafka:7.1.1] - Container confluentinc/cp-kafka:7.1.1 started in PT0.6145648S
```

**Comment by edysli** [comment] 2022-10-12 22:08
I've tried to reproduce this issue by updating the container images used in `KafkaContainerTest` to the latest ones from Confluent (7.2.2), but the tests in this class still pass... :/ See #5989. I also tried with 6.2.2 and 7.0.1, still no errors.
Is this the wrong of approaching this problem?

**Comment by eddumelendez** [comment] 2022-10-13 03:37
Thanks for looking at this @edysli ! Looks like can not be replicated.

just saw the configuration used in `reactor-kafka` and try to replicate the issue with the tags mentioned but couldn't replicate it. See [this](https://github.com/eddumelendez/testcontainers-kafka-gha-test/blob/main/src/test/java/org/example/KafkaContainerTest.java#L34-L42) and all test passed in [GHA](https://github.com/eddumelendez/testcontainers-kafka-gha-test/actions/runs/3239473096). 

@simonbasle can we give it another try?

**Comment by simonbasle** [comment] 2022-10-17 09:40
this appears to work again in our tests with both `6.2.2` and `6.2.7` versions of the image, so I think this can be closed 👍

**Comment by eddumelendez** [comment] 2022-10-17 13:58
Thanks Simon! I will close it.

**Closed by eddumelendez** 2022-10-17 13:58 UTC
Labels: type/bug, hacktoberfest, modules/kafka

**Comment by msilb** [comment] 2022-11-17 08:24
We have exactly same issue with Docker Desktop. It works fine when running on Linux in our CI/CD pipeline but locally the cp-kafka container fails to start:

```
2022-11-17 09:19:59.876  INFO   --- [    Test worker] d.a.s.com/confluentinc/cp-kafka:7.2.2]   : Creating container for image: docker.artifact.swissre.com/confluentinc/cp-kafka:7.2.2
2022-11-17 09:19:59.938  INFO   --- [    Test worker] d.a.s.com/confluentinc/cp-kafka:7.2.2]   : Container docker.artifact.swissre.com/confluentinc/cp-kafka:7.2.2 is starting: 48d8dcc192307439dbac575a27b47013288537f3276fbcf1c6534a823299d56d
2022-11-17 09:20:22.828  WARN   --- [ntainers-wait-0] .c.w.i.InternalCommandPortListeningCheck : An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection to 127.0.0.1 failed: Connection timed out.
Ncat: Trying next address...
Ncat: Cannot assign requested address.
)
2022-11-17 09:20:22.829  INFO   --- [    Test worker] d.a.s.com/confluentinc/cp-kafka:7.2.2]   : Container docker.artifact.swissre.com/confluentinc/cp-kafka:7.2.2 started in PT22.9565253S
2022-11-17 09:20:23.454 ERROR   --- [    Test worker] d.a.s.com/confluentinc/cp-kafka:7.2.2]   : Could not start container

com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"Container 48d8dcc192307439dbac575a27b47013288537f3276fbcf1c6534a823299d56d is not running"}
```

For us it seems unrelated to the version of the cp-kafka image. Has anyone else faced similar issue with Testcontainers? What could be a workaround?

**Comment by sacsar** [comment] 2023-12-07 20:53
For posterity, I just hit this issue with `testcontainers-java` 1.19.3 (and a few different kafka image versions). The issue was having run out of Docker disk space and was solved by `docker system prune`.
