### ISSUE TITLE
@Testcontainers extension does not work with TestInstance.Lifecycle.PER_CLASS

### ISSUE THREAD

**Issue by alex-arana** [testcontainers/testcontainers-java#2493] opened 2020-03-30 23:30 UTC
The `@Testcontainers` annotation is used in conjunction with the `@Container` annotation to mark Docker containers that should be managed by the Testcontainers extension.

However, if used with `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` the extension does not seem to work. Here's my test code (kotlin):

```kotlin
@Testcontainers
@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
abstract class BaseApplicationIntegrationTest {
    companion object {
        @JvmStatic
        @Container
        private val localStackContainer: LocalStackContainer =
            LocalStackContainer().withServices(LocalStackContainer.Service.SQS)

        @JvmStatic
        @DynamicPropertySource
        private fun localStackProperties(dynamicPropertyRegistry: DynamicPropertyRegistry) {
            localStackContainer.getEndpointConfiguration(LocalStackContainer.Service.SQS)?.let {
                dynamicPropertyRegistry.add("my-service.aws.sqsEndpoint") { it.serviceEndpoint }
            }
        }
    }
}
```

**Comment by bsideup** [comment] 2020-03-31 11:14
Hi @alex-arana,

Please explain "does not seem to work". What you observe?

**Comment by alex-arana** [comment] 2020-04-05 08:08
I get the following error on the console:

```
Caused by: java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:125)
	at org.testcontainers.containers.localstack.LocalStackContainer.getEndpointConfiguration(LocalStackContainer.java:115)
	at com.example.server.BaseApplicationIntegrationTest$Companion.localStackProperties(BaseApplicationIntegrationTest.kt:23)
	at com.example.server.BaseApplicationIntegrationTest$Companion.access$localStackProperties(BaseApplicationIntegrationTest.kt:14)
	at com.example.server.BaseApplicationIntegrationTest.localStackProperties(BaseApplicationIntegrationTest.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.test.context.support.DynamicPropertiesContextCustomizer.lambda$buildDynamicPropertiesMap$3(DynamicPropertiesContextCustomizer.java:86)
	at java.base/java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
	at org.springframework.test.context.support.DynamicPropertiesContextCustomizer.buildDynamicPropertiesMap(DynamicPropertiesContextCustomizer.java:84)
	at org.springframework.test.context.support.DynamicPropertiesContextCustomizer.customizeContext(DynamicPropertiesContextCustomizer.java:73)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:315)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 82 more
```

**Comment by alex-arana** [comment] 2020-04-05 08:26
I have uploaded an application sample to demonstrate the issue:
https://gitlab.com/alex.arana/oauth2-client-service/-/tree/testcontainers-issue-2493

**Comment by elijah-pl** [comment] 2020-06-15 17:03
@alex-arana Did you manage to find a workaround?

**Comment by alex-arana** [comment] 2020-09-10 00:55
This issue is related to #2290 which has been automatically marked as stale. There is no viable workaround except to remove ```@TestInstance(TestInstance.Lifecycle.PER_CLASS)``` from the Test.

**Comment by alex-arana** [comment] 2020-09-10 12:31
I've verified that the test succeeds when using `TestInstance.Lifecycle.PER_METHOD` (default):

```kotlin
@Testcontainers
@SpringBootTest
internal class DockerIntegrationTest {
    companion object : KLogging() {
        @JvmStatic
        @Container
        private val localStackContainer: LocalStackContainer =
            LocalStackContainer().withServices(LocalStackContainer.Service.SQS)

        @JvmStatic
        @DynamicPropertySource
        fun localstackProperties(registry: DynamicPropertyRegistry) {
            localStackContainer.getEndpointConfiguration(LocalStackContainer.Service.SQS).let {
                logger.debug("SQS endpoint configuration: serviceEndpoint='${it.serviceEndpoint}'")
                registry.add("test-adapter-service.aws.sqs-endpoint") { it.serviceEndpoint }
            }
        }
    }

    @Test
    fun test(@Autowired environment: Environment) {
        assertThat(environment.getProperty("test-adapter-service.aws.sqs-endpoint")).isNotBlank
    }
}
```

**Comment by bsideup** [comment] 2020-11-11 10:45
@alex-arana as suggested in #2290, you can also use the singleton container approach.

**Comment by bsideup** [comment] 2020-11-11 10:46
Duplicate of #2290

**Closed by bsideup** 2020-11-11 10:46 UTC
Labels: modules/jupiter, resolution/waiting-for-info, type/question

**Comment by amirmv2006** [comment] 2021-01-07 19:18
I had a similar problem with another JUnit 5 extension I wrote and I found out when tests are run in `TestInstance.Lifecycle.PER_CLASS` Spring's application context will be loaded before the `org.junit.jupiter.api.extension.BeforeAllCallback#beforeAll` is called. I solved that by moving my logic to `org.junit.jupiter.api.extension.TestInstancePostProcessor#postProcessTestInstance`, does it also make sense to start the "Shared Containers" on `postProcessTestInstance`? I think that would solve this problem
