### ISSUE TITLE
Crash on Macbook M1 with arm openjdk 15.0.2

### ISSUE THREAD

**Issue by don41382** [testcontainers/testcontainers-java#3954] opened 2021-04-01 10:06 UTC
I am working with the following configuration:

- **MacBook:** Macbook Air M1 8-Cores, 16 GB
- **MacOs:** BigSur: 11.2.3
- **JDK:** OpenJDK 15.0.2, build for arm
- **testcontainer:** 1.15.2

This configuration works flawless, when I am choosing the intel build for the same JDK. I also tried different vendors like zulu and bellsoft, but I have the same issue.

Crash in my test, where I try to boot up a postgres database.
```
11:56:12.033 [error] - [DockerClientProviderStrategy.java:208] - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
11:56:12.035 [error] - [DockerClientProviderStrategy.java:210] -     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.UnsatisfiedLinkError: xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: dlopen(xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp, 1): no suitable image found.  Did find:
	xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: no matching architecture in universal wrapper
	xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: no matching architecture in universal wrapper). Root cause UnsatisfiedLinkError (xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: dlopen(xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp, 1): no suitable image found.  Did find:
	xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: no matching architecture in universal wrapper
	xxx/Library/Caches/JNA/temp/jna10508881016752442198.tmp: no matching architecture in universal wrapper)
11:56:12.035 [error] - [DockerClientProviderStrategy.java:210] -     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.NoClassDefFoundError: Could not initialize class org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory$1). Root cause NoClassDefFoundError (Could not initialize class org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory$1)
11:56:12.035 [error] - [DockerClientProviderStrategy.java:212] - As no valid configuration was found, execution cannot 
```

Any ideas?

**Comment by bsideup** [comment] 2021-04-01 10:23
Duplicate of #3610

**Closed by bsideup** 2021-04-01 10:23 UTC
