### ISSUE TITLE
Quickstart Jupiter Docu does not work.

### ISSUE THREAD

**Issue by jschnasse** [testcontainers/testcontainers-java#3307] opened 2020-10-05 09:59 UTC
The jupiter quickstart example on testcontainers.org refers to version 1.14.3 but runs only with release candidate of 1.15.0

This has the potential to slow down the quickstart....

See also:

https://stackoverflow.com/questions/64204602/testcontainers-quickstart-example-does-not-work

**Comment by bsideup** [comment] 2020-10-05 15:37
Duplicate of #3166

**Closed by bsideup** 2020-10-05 15:37 UTC
