### ISSUE TITLE
Remove dependency on JUnit 4 API in Testcontainers core

### ISSUE THREAD

**Issue by gastaldi** [testcontainers/testcontainers-java#3756] opened 2021-02-04 19:36 UTC
It would be nice if `Testcontainers core` didn't depend on the JUnit 4 API (`junit:junit:4.12`), given that this dependency is available even when your tests only depend on the `junit-jupiter` dependency.

**Comment by bsideup** [comment] 2021-02-04 22:10
Duplicate of #970

**Closed by bsideup** 2021-02-04 22:10 UTC

**Comment by gastaldi** [comment] 2021-02-04 22:19
Oops, I missed that one while searching. Thanks!
