### ISSUE TITLE
testcontainers and rest-assured collision on hamcrest / hamcrest-core

### ISSUE THREAD

**Issue by rsvoboda** [testcontainers/testcontainers-java#5287] opened 2022-04-28 11:40 UTC
testcontainers and rest-assured collision on hamcrest / hamcrest-core

```
+- org.testcontainers:testcontainers:jar:1.17.1:test
|  +- junit:junit:jar:4.13.2:test
|  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
```
```
\- io.rest-assured:rest-assured:jar:4.5.1:test
   +- org.hamcrest:hamcrest:jar:2.1:test
```

These two artifacts may cause a collision, e.g. when `testcontainers` are on the classpath and `org.hamcrest.Matchers.containsStringIgnoringCase` is used in a test.

**Ask:**
Please provide `org.testcontainers:testcontainers` artifact variant compatible with JUnit5 / not depending on JUnit4.

There is `org.testcontainers:junit-jupiter` artifact, but it doesn't solve the deps issue - JUnit4 and hamcrest-core are still present:
```
[INFO] \- org.testcontainers:junit-jupiter:jar:1.17.1:test
[INFO]    +- org.testcontainers:testcontainers:jar:1.17.1:test
[INFO]    |  +- junit:junit:jar:4.13.2:test
[INFO]    |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    |  +- org.apache.commons:commons-compress:jar:1.21:test
[INFO]    |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:test
[INFO]    |  |  \- org.jetbrains:annotations:jar:17.0.0:test
[INFO]    |  +- com.github.docker-java:docker-java-api:jar:3.2.13:test
[INFO]    |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:test
[INFO]    |  \- com.github.docker-java:docker-java-transport-zerodep:jar:3.2.13:test
[INFO]    |     +- com.github.docker-java:docker-java-transport:jar:3.2.13:test
[INFO]    |     \- net.java.dev.jna:jna:jar:5.8.0:test
[INFO]    \- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO]       +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]       +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO]       \- org.apiguardian:apiguardian-api:jar:1.1.2:test
```

Original issue was filed for Quarkus - https://github.com/quarkusio/quarkus/issues/25171

**Comment by eddumelendez** [comment] 2022-04-29 19:40
Hi @rsvoboda, thanks for raising the issue. I think quarkus can force the hamcrest version which I can not see it [here](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml)

**Comment by bsideup** [comment] 2022-04-29 19:42
This also looks like a duplicate of https://github.com/testcontainers/testcontainers-java/issues/970

We do want to remove JUnit from our dependency tree but that will come later as Testcontainers 2.0 (we already started working on some of it)

**Comment by eddumelendez** [comment] 2022-11-14 14:10
Closing as duplicated

**Closed by eddumelendez** 2022-11-14 14:10 UTC
