### ISSUE TITLE
Linux: cannot connect to localhost from Docker container

### ISSUE THREAD

**Issue by realulim** [testcontainers/testcontainers-java#3412] opened 2020-10-29 11:56 UTC
I have a standard Selenium-based test suite which runs against http://localhost:8080 using a local Chrome browser via a System Property BASE_URL. I tried to introduce testcontainers, but the containerized Chrome could not connect to my webapp. I tried three methods.

First method:
```
Testcontainers.exposeHostPorts(8080);
System.setProperty(BASEURL, "http://host.testcontainers.internal:8080");
```
I am getting the error message: org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
The browser screenshot:
![screenshot](https://user-images.githubusercontent.com/17084846/97565066-e1b6f080-19e5-11eb-87d9-731c580a309b.png)

Second method:

`System.setProperty(BASEURL, "http://" + chrome.getTestHostIpAddress() + ":8080");`

The error message here: java.lang.UnsupportedOperationException: getTestHostIpAddress() is only implemented for docker-machine right now

This I find weird, because I thought this was an issue for Mac/Windows only, but I am running Fedora 29.

Third method:
After installing docker-machine I get this error message: org.testcontainers.shaded.org.zeroturnaround.exec.InvalidExitValueException: Unexpected exit value: 1, allowed exit values: [0], executed command [docker-machine, ssh, trip1, echo $SSH_CONNECTION], output was 23 bytes:
machine does not exist

**Comment by bsideup** [comment] 2020-10-29 12:55
Make sure that you call `exposeHostPorts` _before_ starting the browser container, as per https://www.testcontainers.org/features/networking/#exposing-host-ports-to-the-container

**Comment by bsideup** [comment] 2020-10-29 12:55
Also, see this example:
https://github.com/testcontainers/testcontainers-java/blob/master/examples/selenium-container/src/test/java/SeleniumContainerTest.java

**Comment by realulim** [comment] 2020-10-29 13:07
That is the example I followed: https://github.com/selenide-examples/testcontainers/blob/master/src/test/java/org/selenide/examples/GoogleTestWithDocker.java

**Comment by bsideup** [comment] 2020-10-29 13:10
@realulim okay 😅 Yet, I suggest you to check the example I shared, because the order is important.
For the order, check how JUnit's `@Rule` works, this isn't Testcontainers specific.

**Comment by realulim** [comment] 2020-10-29 15:00
I replicated the example as best I could (I don't have the Spring Boot Test framework), but the error message is the same. Maybe this method just doesn't work with Selenide.

What about the other two methods?

**Comment by bsideup** [comment] 2020-10-29 15:17
@realulim the method works with any framework and does not depend on Spring Boot. Just make sure that you call `exposeHostPorts` before the container started. e.g. put a break point and debug.

**Comment by realulim** [comment] 2020-10-29 18:26
How I can see in the debugger when the container starts? That happens outside the JVM. If I knew which command starts the container, then I could verify. That's why I asked above when the container starts, but I didn't understand your answer.

**Comment by bsideup** [comment] 2020-10-29 19:51
@realulim see `GenericContainer#start`

**Comment by realulim** [comment] 2020-10-30 09:52
Thank you for your help. I looked at the code, but am not sure how that relates to my first method. It's probably more complicated than I thought, so I'd need to supply a standalone test case, which I currently don't have. If the second and third method are indeed expected behavior, then that should perhaps be documented and then the issue could be closed.

**Comment by bsideup** [comment] 2020-10-30 13:12
@realulim `getTestHostIpAddress` is obsolete and will be deprecated soon and worked in a small subset of supported environments (docker-machine)

the error message you're getting is just a logging and does not prevent the tests from starting, right?
It seems that you don't have a default Docker Machine created, hence `1` exit code.

Once again, instead of looking into docker-machine, I would recommend you to double check your code and ensure that the order is correct. Since it does not seem to be related to Testcontainers, I am going to close this issue unless you have a reproducer demonstrating that `exposeHostPorts` called *before* the target container does not work.

**Closed by bsideup** 2020-10-30 13:12 UTC
