### ISSUE TITLE
Conflicts in versions of used libraries net.java.dev.jna

### ISSUE THREAD

**Issue by artemtere** [testcontainers/testcontainers-java#3751] opened 2021-02-01 13:20 UTC
Testcontainers has two libs which use `net.java.dev.jna` of different versions which can potentially be a problem.
![image](https://user-images.githubusercontent.com/23436851/106464056-34062280-64a9-11eb-9e94-18a52217579f.png)

**Comment by bsideup** [comment] 2021-02-01 13:23
Duplicate of #3308

**Closed by bsideup** 2021-02-01 13:23 UTC
