### ISSUE TITLE
DockerImageName getRepository returns repo and image name

### ISSUE THREAD

**Issue by KyleAure** [testcontainers/testcontainers-java#5194] opened 2022-04-01 20:00 UTC
Using TestContainers 1.16.3

If I create a synthetic image using ImageFromDockerFile: 

```java
public static ImageFromDockerfile synteticImage = new ImageFromDockerfile()
                .withDockerfile(Paths.get("lib/LibertyFATTestFiles/postgres/Dockerfile"));

@ClassRule
public static GenericContainer<?> container = new GenericContainer<>(synteticImage) //
                .withExposedPorts(POSTGRE_PORT)
                .withEnv("POSTGRES_DB", POSTGRES_DB)
                .withEnv("POSTGRES_USER", POSTGRES_USER)
                .withEnv("POSTGRES_PASSWORD", POSTGRES_PASSWORD)
                .withLogConsumer(new SimpleLogConsumer(ContainersTest.class, "postgres"))
                .waitingFor(new LogMessageWaitStrategy()
                                .withRegEx(".*database system is ready to accept connections.*\\s")
                                .withTimes(2)
                                .withStartupTimeout(Duration.ofSeconds(60)));
```

And run the following test: 

```java
@Test
public void ensureSyntheticImageName() {
    DockerImageName name = DockerImageName.parse(container.getDockerImageName());

    Log.info(SyntheticImageTest.class, "ensureSyntheticImageName", name.asCanonicalNameString());

    //Example: localhost/testcontainers/jxbqdhfgsomphxr5:latest
    assertEquals("localhost", name.getRegistry()); //localhost
    assertEquals("testcontainers", name.getRepository()); //testcontainers
    assertEquals("latest", name.getVersionPart()); //latest
}
```

My test fails with:

```txt
2022-04-01-14:58:08:593 expected:<testcontainers[]> but was:<testcontainers[/jxbqdhfgsomphxr5]> 
```

Meaning that DockerImageName.getRepository() is returning both the repository and container name which is what  getUnversionedPart() should return.

**Comment by kiview** [comment] 2022-04-04 10:26
Thanks for the example. I'm inclined to say, it works as intended. In this case, the repository part of the image is indeed `testcontainers/jxbqdhfgsomphxr5`. Also, see the Docker docs:
https://docs.docker.com/glossary/#repository

I'll close the issue therefore, but feel free to comment if you think I am missing something.🙂

**Closed by kiview** 2022-04-04 10:26 UTC
