### ISSUE TITLE
 The command 'apt-get update' on ubuntu contaniner exit code was 126.

### ISSUE THREAD

**Issue by CarlosZzzz** [testcontainers/testcontainers-java#4077] opened 2021-05-12 05:25 UTC
That was don't stop suddenly, but my first command 'apt-get update' exit code still was 126.
Whats wrong with it? thx for help
log is :

> 08:52:55.788 [main] DEBUG org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: Running "exec" command: apt-get update
08:52:55.788 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9,<null>,true,true,<null>,<null>,<null>,{apt-get update},<null>,<null>
08:52:55.788 [main] TRACE org.testcontainers.shaded.com.github.dockerjava.core.exec.ExecCreateCmdExec - POST: DefaultWebTarget{path=[/containers/1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9/exec], queryParams={}}
08:52:55.956 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 87b1b7548a849daaf11741e0f98b83eb155d2fb9a2d6fad6526615d761c7f471
08:52:55.957 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectExecCmdExec - GET: DefaultWebTarget{path=[/exec/87b1b7548a849daaf11741e0f98b83eb155d2fb9a2d6fad6526615d761c7f471/json], queryParams={}}
08:52:55.969 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stdout: OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"apt-get update\": executable file not found in $PATH": unknown
08:52:55.969 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stderr: 
08:52:55.970 [main] DEBUG org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: Running "exec" command: apt-get install -y p0f
08:52:55.970 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9,<null>,true,true,<null>,<null>,<null>,{apt-get,install,-y,p0f},<null>,<null>
08:52:55.970 [main] TRACE org.testcontainers.shaded.com.github.dockerjava.core.exec.ExecCreateCmdExec - POST: DefaultWebTarget{path=[/containers/1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9/exec], queryParams={}}
08:52:56.200 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6b90945d6cb87d964fdac1e56adf557b33a20f1d8b469bbf4312cc381814627c
08:52:56.201 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectExecCmdExec - GET: DefaultWebTarget{path=[/exec/6b90945d6cb87d964fdac1e56adf557b33a20f1d8b469bbf4312cc381814627c/json], queryParams={}}
08:52:56.208 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stdout: Reading package lists...
Building dependency tree...
Reading state information...
08:52:56.209 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stderr: E: Unable to locate package p0f
08:52:56.211 [main] DEBUG org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: Running "exec" command: sh p0f.sh start
08:52:56.212 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9,<null>,true,true,<null>,<null>,<null>,{sh,p0f.sh,start},<null>,<null>
08:52:56.212 [main] TRACE org.testcontainers.shaded.com.github.dockerjava.core.exec.ExecCreateCmdExec - POST: DefaultWebTarget{path=[/containers/1d647ff745e25547a6ee269505c546c017f3f16b19c0f32447504d7d78001eb9/exec], queryParams={}}
08:52:56.458 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6e9284781d4de451efb56d2b28daa9db6a4c8c1d1290b21af3ad20c73d4426f1
08:52:56.459 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectExecCmdExec - GET: DefaultWebTarget{path=[/exec/6e9284781d4de451efb56d2b28daa9db6a4c8c1d1290b21af3ad20c73d4426f1/json], queryParams={}}
08:52:56.465 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stdout: 
08:52:56.465 [main] TRACE org.testcontainers.containers.ExecInContainerPattern - /reverent_kalam: stderr: p0f.sh: 12: p0f: not found

_Originally posted by @CarlosZzzz in https://github.com/testcontainers/testcontainers-java/issues/4075#issuecomment-839346495_

**Comment by bsideup** [comment] 2021-05-12 06:13
Duplicate of #4075

**Closed by bsideup** 2021-05-12 06:13 UTC
