### ISSUE TITLE
Hard dependency on junit4 Rules

### ISSUE THREAD

**Issue by avillev** [testcontainers/testcontainers-java#2083] opened 2019-11-18 07:41 UTC
Version: 1.12.3

```java
@Container
public static KafkaContainer kafka = new KafkaContainer(TestContainerHelper.TEST_KAFKA_CONTAINER_VERSION);
```

The test containers (in my case Kafka) extend from 'GenericContainer'. 
Then we have:

**GenericContainer extends FailureDetectingExternalResource implements TestRule**

The problem is that when you are trying to get rid of all your junit4 dependencies it fails at runtime.
The library is compatible Junit5 but this is an annoying restriction for people who want to migrate 100%.

**Comment by bsideup** [comment] 2019-11-18 07:42
Duplicate of https://github.com/testcontainers/testcontainers-java/issues/970

**Closed by bsideup** 2019-11-18 07:42 UTC

**Comment by avillev** [comment] 2019-11-18 07:44
Wow. That reaction was almost real-time !!

**Comment by bsideup** [comment] 2019-11-18 09:14
Was doing my morning issue checking and yours was just submitted :)
