### ISSUE TITLE
[Bug]: Container is Dead (Ryuk)

### ISSUE THREAD

**Issue by nefilim** [testcontainers/testcontainers-java#6078] opened 2022-10-28 20:53 UTC
### Module

Core

### Testcontainers version

1.17.5

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client:
   Version:           20.10.17
   API version:       1.41
   Go version:        go1.18.6
   Git commit:        100c701
   Built:             Wed Sep 28 23:10:17 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.17
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.18.6
    Git commit:       a89b842
    Built:            Wed Sep 28 23:10:55 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.4.6
    GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
   runc:
    Version:          1.1.3
    GitCommit:        1e7bb5b773162b57333d57f612fd72e3f8612d94
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
```

### What happened?

This is happening intermittently on GitHub Actions, more likely when multiple runs are happening concurrently: 

```
  org.testcontainers.containers.ContainerLaunchException: Container startup failed
  at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
  at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
  at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
  at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
  at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
  at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:69)
  at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
  at com.xxx.capacity.test.testcontainers.TestContainers$.$anonfun$createNetworkResource$3(TestContainers.scala:96)
  at org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$info$5(Slf4jLoggerInternal.scala:91)
  at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$info$4(Slf4jLoggerInternal.scala:91)
  ...
  Cause: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
  at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
  at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
  at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
  at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
  at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
  at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
  at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:69)
  at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
  at com.xxx.capacity.test.testcontainers.TestContainers$.$anonfun$createNetworkResource$3(TestContainers.scala:96)
  at org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$info$5(Slf4jLoggerInternal.scala:91)
  ...
  Cause: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
  at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
  at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
  at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
  at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
  at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
  at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
  at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
  at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
  at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:69)
  at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
  ...
  Cause: java.lang.IllegalStateException: Container is dead
  at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:501)
  at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
  at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
  at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
  at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
  at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
  at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
  at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
  at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:69)
  at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
  ...
```

**Comment by kiview** [comment] 2022-11-02 16:16
If you run multiple tests in parallel, it might be the case that you are running out of resources. Can you share more details on your actual setup and maybe even a reproducer?

**Comment by nefilim** [comment] 2022-11-03 13:58
Maybe running out of resources is a concern but seems to be unlikely. Just this morning it happened with a single run, no other runs within hours. 

We have a dedicated `m5.4xlarge` EC2 instance (16 core, 64GB of memory) allocated to this specific organization as GHA runner. Here's the typical resource utilization running locally:

<img width="1357" alt="Screenshot 2022-11-02 at 10 28 08" src="https://user-images.githubusercontent.com/992282/199740228-7fce286c-0949-46ae-bc91-0dddde4831dd.png">

I suspect it's the same problem again, container output isn't attached properly to the JVM process, I neglected to include this line from the logs:

```
02:23:11.793 [io-compute-3] ERROR 🐳 [testcontainers/ryuk:0.3.4] - There are no stdout/stderr logs available for the failed container
```

**Comment by nefilim** [comment] 2022-11-03 15:26
I was able to work with someone in our GitHub team and look at the runner host itself. 

This particular branch is now failing repeatedly (even after restarting the docker daemon) on the same test suite (third one in) and we were able to determine that the `ryuk` docker container does start up but is not showing any logs (assuming the `docker` CLI util uses the same API to the daemon that the docker-java library uses for logs).

<img width="1599" alt="Screenshot 2022-11-03 at 08 55 40" src="https://user-images.githubusercontent.com/992282/199758063-369e6d92-65b0-4126-8a03-301cf42e9f89.png">

`docker ps -a` showed nothing running and `top` showed meaningless resource utilization in terms of CPU & memory on the host after each failed run completed. 

After restarting the whole EC2 instance the problem disappeared again, so something got into a bad state appears to have reset?

**Comment by villevaltonen** [comment] 2022-11-09 06:03
I wonder if this is an issue with Ryuk itself (or Docker in Docker in my case), because I've seen similar issues with `testcontainers-go`. Ryuk starts, but the test suite hangs on waiting it to start. If I the skip reaper container creation i.e. Ryuk, I can proceed with my test suite.

**Comment by kiview** [comment] 2022-11-14 14:50
This will be something hard to debug. I have a hunch that this occurs when multiple `ryuk` containers are created/started simultaneously and try to mount the Docker socket file. At one point, this leaves something in the Docker daemon in a weird state.

@nefilim Since I am not an expert on hosted GHA runners, how does Docker become accessible to your jobs? Does GHA mount the host Docker socket into the job containers, or is it a DinD setup? Also, if this happens again, could you try to only restart the Docker daemon instead of the whole machine?

**Comment by nefilim** [comment] 2022-11-14 15:02
>  Also, if this happens again, could you try to only restart the Docker daemon instead of the whole machine?

That was the first step, unfortunately it did not help .. quite strange. 

> This particular branch is now failing repeatedly (even after restarting the docker daemon)

**Comment by kiview** [comment] 2022-11-21 15:34
@nefilim Do you have any suggestion how we can reproduce it? Maybe even a way to reproduce it locally, either with a Linux host or a Docker Desktop installation? Else, I am not sure how we can proceed in triaging this issue.

**Comment by kiview** [comment] 2022-12-19 14:33
In the light of this comment https://github.com/testcontainers/testcontainers-java/issues/5978#issuecomment-1337528540, I am closing the issue, assuming the change in the build agent hardware mitigated the issue. 

Please let us know if the issue persists and we can re-open @nefilim.

**Closed by kiview** 2022-12-19 14:33 UTC
Labels: type/bug
