### ISSUE TITLE
Why some classpath properties are ignored?

### ISSUE THREAD

**Issue by mxv2** [testcontainers/testcontainers-java#2365] opened 2020-02-19 13:25 UTC
Hello.
Thank you for your work and project.

Why some properties (more interesting in `checks.disable`) are ignored from classpath?
What's the point?

If I don't want disable docker check globally, but for my specific project, why I can't?
(I saw reasoning in https://github.com/testcontainers/testcontainers-java/pull/1784, but didn't understand these)

**Comment by bsideup** [comment] 2020-02-19 13:27
Because there are environment-specific properties. If you disable them per project, then other users of that project (especially the ones who just cloned it for the first time) may experience issues and will miss some helpful information that the checks provide.

Duplicate of #2312.

**Closed by bsideup** 2020-02-19 13:27 UTC
Labels: type/question

**Comment by mxv2** [comment] 2020-02-19 13:39
Okay, I know reason now, it's good point.
But I didn't understand from documentation that checks.disable is **only** environment setting.
And I spent a lot of time because of this misusing.

Will you accept PR with warning log about this misusing properties (and fix doc maybe)?

**Comment by bsideup** [comment] 2020-02-19 13:43
@mxv2 absolutely! 💯 

Even more - we already discussed this idea, see this thread https://github.com/testcontainers/testcontainers-java/pull/1781#discussion_r369165730 for the details :)

**Comment by bsideup** [comment] 2020-02-19 13:44
And sorry that it caused a time waste for you ☺️
