### ISSUE TITLE
ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy())

### ISSUE THREAD

**Issue by the-bug** [testcontainers/testcontainers-java#3464] opened 2020-11-12 11:06 UTC
Hello :)
we are using testcontainers in our build process for integration testing. 
The build is executed on a jenkins server with maven.

If the jenkins server is under heavy load (high CPU and RAM utilization) than some strange error is happening:

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

The corresponding docker image is build via the `DockerfileBuilder` from a base image that is in the local repository.  The base image was build before with `io.fabric8.docker-maven-plugin`.

The jenkins server is behind a firewall which drops the packages. This may be the answer for the `Client.Timeout`.
For me it is strange that `imageName=<resolving>`. I would expect here some name...

I am using version `1.15.0` of `org.testcontainers.testcontainers`

What information can I further provide?

Thanks for any help in advance!

**Comment by bsideup** [comment] 2020-11-12 11:08
`imageName=<resolving>` is because the image is created from `Future<?>` and, before it is resolved, we don't know the image id.

Since the error comes from Docker, and, as you said, the firewall drops the packages, I will close the issue since it does not look like an issue with Testcontainers.

**Closed by bsideup** 2020-11-12 11:08 UTC

**Comment by the-bug** [comment] 2020-11-16 08:44
@bsideup thank you for the answer!

But I do not quite understand yet...
testcontainers is responsible for the image name resolution, isn't it?

The error is occurring if there is some load on the machine e.g. two or more jenkins jobs are running. If there is not much load this error does not appear. 
`https://registry-1.docker.io/v2` should not be called as it is not needed in our test. 

My suggestion is that somehow the iamgeName is not properly resolved and thus `https://registry-1.docker.io/v2` is called as a default or something.

@bsideup can you point me some direction? Do you think I should somehow debug `org.testcontainers.images.RemoteDockerImage.resolve()` and `org.testcontainers.images.builder.ImageFromDockerfile.resolve()`, may this be a problem of `com.github.dockerjava.api` or where can I proceed?

**Comment by bsideup** [comment] 2020-11-16 08:48
@the-bug try fixing the firewall issue (dropping packages)

Also, your images may not be from Docker Hub, but we use a few images to make Testcontainers work (such as Ryuk) that will be pulled from `https://registry-1.docker.io/v2`. Consider either configuring a mirror, [setting the images explicitly](https://www.testcontainers.org/features/configuration/#customizing-images) or using the [Image Name Substitution](https://www.testcontainers.org/features/image_name_substitution/) feature.

**Comment by the-bug** [comment] 2020-11-16 09:16
@bsideup  thx again for the answer
We have a own docker repository(mirror) in the network which is used instead of `https://registry-1.docker.io/v2` so I do not think the firewall is the problem.

**Comment by the-bug** [comment] 2020-11-16 13:03
It seems to work now. But I do not think that this should be expected behavior...

In our build we use the `io.fabric8.docker-maven-plugin` to build the images used by testcontainers. The image name was 'imageForTest' and is now 'mirror.intern/imageForTest'. Adding the 'mirror.intern' (which does exists and is reachable in our network) fixes the problem. I think this is so as with no mirror specifier 'docker.io' is used as default.
But the image is not pushed to 'mirror.intern' instead it is in the local repository. 

I would expect testcontainers to run if the image is in the local repository/cache no matter if the the (default-)repository is reachable. I still do not know if this is an issue of testcontainers.

@bsideup thanks for the help and the fingerpoints to the right direction!

**Comment by bsideup** [comment] 2020-11-16 13:20
if you only need to use a local image, you can set the image pull policy to never pull. Perhaps that's why it was trying to connect to Docker Hub

Otherwise, a reproducer would be highly appreciated because it becomes a bit hard to understand the behaviour described and what the issue is about :)

**Comment by the-bug** [comment] 2020-11-16 13:40
The pull policy is a good point.

I will try to set up a reproducer on the weekend. But this may be not deterministic...

Thx again!
