### ISSUE TITLE
Resolve issues with Docker Compose when running under Docker for Windows

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#306] opened 2017-03-03 08:24 UTC
Re [this](https://github.com/testcontainers/testcontainers-java/pull/297#issuecomment-282163199) on #297, it seems that Docker Compose has an issue when using Docker for Windows.

We are releasing Docker for Windows support so as not to delay any further, but docker compose support still needs to be fixed.

**Comment by kmruiz** [comment] 2017-04-26 22:37
Hi,

I reproduced the problem on my Windows 10 machine when using docker-compose on a docker for some tests. I downloaded the source code of the library and found what I think is the problem.

On method org.testcontainers.containers.GenericContainer#addFileSystemBind you build a path using MountableFile, but this path is incorrect. On Docker for Windows, this Java process will run on Windows, but the docker runs into a Linux VM under Hyper-V.

Building this path in the wrong way will make docker-compose unable to communicate with the underlying docker system that it's on Linux, because it's using a Windows path.

A fast check is, if you ignore the MountableFile and pass to binds.add the raw hostPath, it will work for almost all Docker-Compose tests. There is one issue with org.testcontainers.junit.DockerComposeOverrideTest#testEnvVar but looks like it's another issue with paths again (but not with docker-compose interaction itself).

Hope this info helps. I will investigate further because I want to use this lib on Windows (on Linux already works fine).

**Comment by kiview** [comment] 2017-04-27 08:22
Nice work :)
You can put the patch in a PR if you like.

**Comment by kmruiz** [comment] 2017-04-27 19:45
I'm trying to solve the problem with the failing test. Looks like there are some problems when resolving file paths when working with Hyper-V because Linux paths need to be written as is, but seems that Windows paths need to be translated to the mount point of Hyper-V.

If I make it work I will send you a PR :)

**Comment by kiview** [comment] 2018-02-26 21:33
This has been fixed some time ago.

**Closed by kiview** 2018-02-26 21:33 UTC
Labels: bug, docker-compose, docker-for-windows, help wanted
