### ISSUE TITLE
Remove JUnit 4 dependency

### ISSUE THREAD

**Issue by pkubowicz** [testcontainers/testcontainers-java#3101] opened 2020-08-14 14:31 UTC
Testcontainers does not run if JUnit 4 is not present on classpath because GenericContainer implements JUnit 4 TestRule.

[Spring Boot 2.4 will remove JUnit 4 from classpath](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4.0-M1-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test). Having both versions of JUnit on classpath is inconvenient for authoring tests, as developer is constantly forced to choose a proper import when typing `@Test` etc.

I think Testcontainers should have a roadmap for releasing a version without JUnit 4 dependency.

**Comment by bsideup** [comment] 2020-08-14 14:32
Duplicate of #970

**Closed by bsideup** 2020-08-14 14:32 UTC
