### ISSUE TITLE
Junit 5 Jupiter artifact should exclude Junit 4.1.3

### ISSUE THREAD

**Issue by hantsy** [testcontainers/testcontainers-java#2826] opened 2020-06-02 05:50 UTC
When adding `org.testcontainers:junit-jupiter` as dependencies, `junit:junit:jar` should be excluded.

```bash
[INFO] +- org.testcontainers:junit-jupiter:jar:1.14.2:test
[INFO] |  +- org.testcontainers:testcontainers:jar:1.14.2:test
[INFO] |  |  +- junit:junit:jar:4.13:test
[INFO] |  |  |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |  |  +- org.jetbrains:annotations:jar:19.0.0:test
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.20:test
[INFO] |  |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:test
[INFO] |  |  +- org.rnorth.visible-assertions:visible-assertions:jar:2.1.2:test
[INFO] |  |  +- org.rnorth:tcp-unix-socket-proxy:jar:1.0.2:test
[INFO] |  |  |  +- com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.0.4:test
[INFO] |  |  |  |  \- org.scijava:native-lib-loader:jar:2.0.2:test
[INFO] |  |  |  \- com.kohlschutter.junixsocket:junixsocket-common:jar:2.0.4:test
[INFO] |  |  \- net.java.dev.jna:jna-platform:jar:5.5.0:test
[INFO] |  |     \- net.java.dev.jna:jna:jar:5.5.0:test
```

**Comment by bsideup** [comment] 2020-06-02 06:09
Duplicate of #970

**Closed by bsideup** 2020-06-02 06:09 UTC
